// HanziQuest — HSK1 Word Data (~150 words)
// Each word: id, hanzi, pinyin, meaning (French), category, hsk, sentences

const HSK_DATA = [
  // === SALUTATIONS (greetings) ===
  { id: 1, hanzi: "你好", pinyin: "nǐ hǎo", meaning: "Bonjour", category: "salutations", hsk: 1, sentences: ["你好，我叫小明。"] },
  { id: 2, hanzi: "谢谢", pinyin: "xiè xie", meaning: "Merci", category: "salutations", hsk: 1, sentences: ["谢谢你！"] },
  { id: 3, hanzi: "再见", pinyin: "zài jiàn", meaning: "Au revoir", category: "salutations", hsk: 1, sentences: ["明天再见！"] },
  { id: 4, hanzi: "对不起", pinyin: "duì bu qǐ", meaning: "Pardon / Désolé", category: "salutations", hsk: 1, sentences: ["对不起，我来晚了。"] },
  { id: 5, hanzi: "没关系", pinyin: "méi guān xi", meaning: "Ce n'est rien", category: "salutations", hsk: 1, sentences: ["没关系，没问题。"] },
  { id: 6, hanzi: "请", pinyin: "qǐng", meaning: "S'il vous plaît", category: "salutations", hsk: 1, sentences: ["请坐。"] },
  { id: 7, hanzi: "不客气", pinyin: "bú kè qi", meaning: "De rien", category: "salutations", hsk: 1, sentences: ["不客气！"] },

  // === PRONOMS (pronouns) ===
  { id: 8, hanzi: "我", pinyin: "wǒ", meaning: "Je / Moi", category: "pronoms", hsk: 1, sentences: ["我是学生。"] },
  { id: 9, hanzi: "你", pinyin: "nǐ", meaning: "Tu / Toi", category: "pronoms", hsk: 1, sentences: ["你好吗？"] },
  { id: 10, hanzi: "他", pinyin: "tā", meaning: "Il / Lui", category: "pronoms", hsk: 1, sentences: ["他是老师。"] },
  { id: 11, hanzi: "她", pinyin: "tā", meaning: "Elle", category: "pronoms", hsk: 1, sentences: ["她很漂亮。"] },
  { id: 12, hanzi: "我们", pinyin: "wǒ men", meaning: "Nous", category: "pronoms", hsk: 1, sentences: ["我们是朋友。"] },
  { id: 13, hanzi: "你们", pinyin: "nǐ men", meaning: "Vous", category: "pronoms", hsk: 1, sentences: ["你们好！"] },
  { id: 14, hanzi: "他们", pinyin: "tā men", meaning: "Ils / Eux", category: "pronoms", hsk: 1, sentences: ["他们是中国人。"] },
  { id: 15, hanzi: "这", pinyin: "zhè", meaning: "Ce / Ceci", category: "pronoms", hsk: 1, sentences: ["这是什么？"] },
  { id: 16, hanzi: "那", pinyin: "nà", meaning: "Ce / Cela", category: "pronoms", hsk: 1, sentences: ["那是我的书。"] },
  { id: 17, hanzi: "哪", pinyin: "nǎ", meaning: "Quel / Lequel", category: "pronoms", hsk: 1, sentences: ["你是哪国人？"] },

  // === NOMBRES (numbers) ===
  { id: 18, hanzi: "一", pinyin: "yī", meaning: "Un (1)", category: "nombres", hsk: 1, sentences: ["我有一个苹果。"] },
  { id: 19, hanzi: "二", pinyin: "èr", meaning: "Deux (2)", category: "nombres", hsk: 1, sentences: ["二月很冷。"] },
  { id: 20, hanzi: "三", pinyin: "sān", meaning: "Trois (3)", category: "nombres", hsk: 1, sentences: ["我有三本书。"] },
  { id: 21, hanzi: "四", pinyin: "sì", meaning: "Quatre (4)", category: "nombres", hsk: 1, sentences: ["四个人。"] },
  { id: 22, hanzi: "五", pinyin: "wǔ", meaning: "Cinq (5)", category: "nombres", hsk: 1, sentences: ["五块钱。"] },
  { id: 23, hanzi: "六", pinyin: "liù", meaning: "Six (6)", category: "nombres", hsk: 1, sentences: ["六点钟。"] },
  { id: 24, hanzi: "七", pinyin: "qī", meaning: "Sept (7)", category: "nombres", hsk: 1, sentences: ["七月很热。"] },
  { id: 25, hanzi: "八", pinyin: "bā", meaning: "Huit (8)", category: "nombres", hsk: 1, sentences: ["八个学生。"] },
  { id: 26, hanzi: "九", pinyin: "jiǔ", meaning: "Neuf (9)", category: "nombres", hsk: 1, sentences: ["九十九。"] },
  { id: 27, hanzi: "十", pinyin: "shí", meaning: "Dix (10)", category: "nombres", hsk: 1, sentences: ["十块钱。"] },
  { id: 28, hanzi: "零", pinyin: "líng", meaning: "Zéro (0)", category: "nombres", hsk: 1, sentences: ["零度。"] },
  { id: 29, hanzi: "两", pinyin: "liǎng", meaning: "Deux (quantité)", category: "nombres", hsk: 1, sentences: ["两个人。"] },
  { id: 30, hanzi: "百", pinyin: "bǎi", meaning: "Cent (100)", category: "nombres", hsk: 1, sentences: ["一百块钱。"] },
  { id: 31, hanzi: "几", pinyin: "jǐ", meaning: "Combien / Quelques", category: "nombres", hsk: 1, sentences: ["你有几本书？"] },
  { id: 32, hanzi: "多少", pinyin: "duō shao", meaning: "Combien", category: "nombres", hsk: 1, sentences: ["这个多少钱？"] },
  { id: 33, hanzi: "个", pinyin: "gè", meaning: "Classificateur général", category: "nombres", hsk: 1, sentences: ["一个人。"] },
  { id: 34, hanzi: "岁", pinyin: "suì", meaning: "Ans (âge)", category: "nombres", hsk: 1, sentences: ["你多大岁数？"] },

  // === TEMPS (time) ===
  { id: 35, hanzi: "今天", pinyin: "jīn tiān", meaning: "Aujourd'hui", category: "temps", hsk: 1, sentences: ["今天天气很好。"] },
  { id: 36, hanzi: "明天", pinyin: "míng tiān", meaning: "Demain", category: "temps", hsk: 1, sentences: ["明天见！"] },
  { id: 37, hanzi: "昨天", pinyin: "zuó tiān", meaning: "Hier", category: "temps", hsk: 1, sentences: ["昨天下雨了。"] },
  { id: 38, hanzi: "年", pinyin: "nián", meaning: "Année", category: "temps", hsk: 1, sentences: ["今年是2024年。"] },
  { id: 39, hanzi: "月", pinyin: "yuè", meaning: "Mois", category: "temps", hsk: 1, sentences: ["一月很冷。"] },
  { id: 40, hanzi: "日", pinyin: "rì", meaning: "Jour / Date", category: "temps", hsk: 1, sentences: ["今天几月几日？"] },
  { id: 41, hanzi: "星期", pinyin: "xīng qī", meaning: "Semaine", category: "temps", hsk: 1, sentences: ["今天星期几？"] },
  { id: 42, hanzi: "现在", pinyin: "xiàn zài", meaning: "Maintenant", category: "temps", hsk: 1, sentences: ["现在几点？"] },
  { id: 43, hanzi: "时候", pinyin: "shí hou", meaning: "Moment", category: "temps", hsk: 1, sentences: ["什么时候去？"] },
  { id: 44, hanzi: "点", pinyin: "diǎn", meaning: "Heure (point)", category: "temps", hsk: 1, sentences: ["现在三点。"] },
  { id: 45, hanzi: "分钟", pinyin: "fēn zhōng", meaning: "Minute", category: "temps", hsk: 1, sentences: ["五分钟。"] },
  { id: 46, hanzi: "上午", pinyin: "shàng wǔ", meaning: "Matin", category: "temps", hsk: 1, sentences: ["上午好！"] },
  { id: 47, hanzi: "下午", pinyin: "xià wǔ", meaning: "Après-midi", category: "temps", hsk: 1, sentences: ["下午三点。"] },
  { id: 48, hanzi: "前面", pinyin: "qián miàn", meaning: "Devant", category: "temps", hsk: 1, sentences: ["学校在前面。"] },
  { id: 49, hanzi: "后面", pinyin: "hòu miàn", meaning: "Derrière", category: "temps", hsk: 1, sentences: ["医院在后面。"] },

  // === FAMILLE (family) ===
  { id: 50, hanzi: "爸爸", pinyin: "bà ba", meaning: "Papa", category: "famille", hsk: 1, sentences: ["我爸爸是医生。"] },
  { id: 51, hanzi: "妈妈", pinyin: "mā ma", meaning: "Maman", category: "famille", hsk: 1, sentences: ["我妈妈做饭。"] },
  { id: 52, hanzi: "儿子", pinyin: "ér zi", meaning: "Fils", category: "famille", hsk: 1, sentences: ["他有一个儿子。"] },
  { id: 53, hanzi: "女儿", pinyin: "nǚ ér", meaning: "Fille (enfant)", category: "famille", hsk: 1, sentences: ["她女儿很漂亮。"] },
  { id: 54, hanzi: "家", pinyin: "jiā", meaning: "Maison / Famille", category: "famille", hsk: 1, sentences: ["我家有五个人。"] },
  { id: 55, hanzi: "人", pinyin: "rén", meaning: "Personne", category: "famille", hsk: 1, sentences: ["这个人是谁？"] },
  { id: 56, hanzi: "朋友", pinyin: "péng you", meaning: "Ami", category: "famille", hsk: 1, sentences: ["他是我的朋友。"] },
  { id: 57, hanzi: "先生", pinyin: "xiān sheng", meaning: "Monsieur", category: "famille", hsk: 1, sentences: ["王先生你好。"] },
  { id: 58, hanzi: "小姐", pinyin: "xiǎo jiě", meaning: "Mademoiselle", category: "famille", hsk: 1, sentences: ["李小姐好漂亮。"] },
  { id: 59, hanzi: "同学", pinyin: "tóng xué", meaning: "Camarade de classe", category: "famille", hsk: 1, sentences: ["他是我的同学。"] },

  // === NOURRITURE (food & drink) ===
  { id: 60, hanzi: "水", pinyin: "shuǐ", meaning: "Eau", category: "nourriture", hsk: 1, sentences: ["我要喝水。"] },
  { id: 61, hanzi: "茶", pinyin: "chá", meaning: "Thé", category: "nourriture", hsk: 1, sentences: ["你喝茶吗？"] },
  { id: 62, hanzi: "米饭", pinyin: "mǐ fàn", meaning: "Riz", category: "nourriture", hsk: 1, sentences: ["我吃米饭。"] },
  { id: 63, hanzi: "菜", pinyin: "cài", meaning: "Légume / Plat", category: "nourriture", hsk: 1, sentences: ["这个菜很好吃。"] },
  { id: 64, hanzi: "水果", pinyin: "shuǐ guǒ", meaning: "Fruit", category: "nourriture", hsk: 1, sentences: ["我喜欢吃水果。"] },
  { id: 65, hanzi: "苹果", pinyin: "píng guǒ", meaning: "Pomme", category: "nourriture", hsk: 1, sentences: ["这个苹果很好吃。"] },
  { id: 66, hanzi: "杯子", pinyin: "bēi zi", meaning: "Tasse / Verre", category: "nourriture", hsk: 1, sentences: ["给我一个杯子。"] },
  { id: 67, hanzi: "钱", pinyin: "qián", meaning: "Argent", category: "nourriture", hsk: 1, sentences: ["多少钱？"] },
  { id: 68, hanzi: "块", pinyin: "kuài", meaning: "Yuan (unité)", category: "nourriture", hsk: 1, sentences: ["十块钱。"] },

  // === VERBES (verbs) ===
  { id: 69, hanzi: "是", pinyin: "shì", meaning: "Être", category: "verbes", hsk: 1, sentences: ["我是学生。"] },
  { id: 70, hanzi: "有", pinyin: "yǒu", meaning: "Avoir", category: "verbes", hsk: 1, sentences: ["我有一本书。"] },
  { id: 71, hanzi: "在", pinyin: "zài", meaning: "Être à / Se trouver", category: "verbes", hsk: 1, sentences: ["他在家。"] },
  { id: 72, hanzi: "去", pinyin: "qù", meaning: "Aller", category: "verbes", hsk: 1, sentences: ["我去学校。"] },
  { id: 73, hanzi: "来", pinyin: "lái", meaning: "Venir", category: "verbes", hsk: 1, sentences: ["请来这里。"] },
  { id: 74, hanzi: "吃", pinyin: "chī", meaning: "Manger", category: "verbes", hsk: 1, sentences: ["我吃苹果。"] },
  { id: 75, hanzi: "喝", pinyin: "hē", meaning: "Boire", category: "verbes", hsk: 1, sentences: ["我喝茶。"] },
  { id: 76, hanzi: "做", pinyin: "zuò", meaning: "Faire", category: "verbes", hsk: 1, sentences: ["你在做什么？"] },
  { id: 77, hanzi: "买", pinyin: "mǎi", meaning: "Acheter", category: "verbes", hsk: 1, sentences: ["我要买书。"] },
  { id: 78, hanzi: "看", pinyin: "kàn", meaning: "Regarder / Voir", category: "verbes", hsk: 1, sentences: ["我看电视。"] },
  { id: 79, hanzi: "听", pinyin: "tīng", meaning: "Écouter", category: "verbes", hsk: 1, sentences: ["我听音乐。"] },
  { id: 80, hanzi: "说", pinyin: "shuō", meaning: "Parler / Dire", category: "verbes", hsk: 1, sentences: ["你说中文吗？"] },
  { id: 81, hanzi: "读", pinyin: "dú", meaning: "Lire", category: "verbes", hsk: 1, sentences: ["我读书。"] },
  { id: 82, hanzi: "写", pinyin: "xiě", meaning: "Écrire", category: "verbes", hsk: 1, sentences: ["我写字。"] },
  { id: 83, hanzi: "喜欢", pinyin: "xǐ huan", meaning: "Aimer", category: "verbes", hsk: 1, sentences: ["我喜欢中国菜。"] },
  { id: 84, hanzi: "想", pinyin: "xiǎng", meaning: "Vouloir / Penser", category: "verbes", hsk: 1, sentences: ["我想去中国。"] },
  { id: 85, hanzi: "能", pinyin: "néng", meaning: "Pouvoir (capacité)", category: "verbes", hsk: 1, sentences: ["你能来吗？"] },
  { id: 86, hanzi: "会", pinyin: "huì", meaning: "Savoir faire", category: "verbes", hsk: 1, sentences: ["我会说中文。"] },
  { id: 87, hanzi: "要", pinyin: "yào", meaning: "Vouloir / Falloir", category: "verbes", hsk: 1, sentences: ["我要一杯茶。"] },
  { id: 88, hanzi: "知道", pinyin: "zhī dào", meaning: "Savoir", category: "verbes", hsk: 1, sentences: ["我不知道。"] },
  { id: 89, hanzi: "认识", pinyin: "rèn shi", meaning: "Connaître", category: "verbes", hsk: 1, sentences: ["很高兴认识你。"] },
  { id: 90, hanzi: "叫", pinyin: "jiào", meaning: "S'appeler", category: "verbes", hsk: 1, sentences: ["我叫小明。"] },
  { id: 91, hanzi: "住", pinyin: "zhù", meaning: "Habiter", category: "verbes", hsk: 1, sentences: ["我住在北京。"] },
  { id: 92, hanzi: "坐", pinyin: "zuò", meaning: "S'asseoir", category: "verbes", hsk: 1, sentences: ["请坐。"] },
  { id: 93, hanzi: "开", pinyin: "kāi", meaning: "Ouvrir / Conduire", category: "verbes", hsk: 1, sentences: ["开门。"] },
  { id: 94, hanzi: "回", pinyin: "huí", meaning: "Retourner", category: "verbes", hsk: 1, sentences: ["我回家了。"] },
  { id: 95, hanzi: "睡觉", pinyin: "shuì jiào", meaning: "Dormir", category: "verbes", hsk: 1, sentences: ["我要睡觉了。"] },
  { id: 96, hanzi: "工作", pinyin: "gōng zuò", meaning: "Travailler", category: "verbes", hsk: 1, sentences: ["他在工作。"] },
  { id: 97, hanzi: "学习", pinyin: "xué xí", meaning: "Étudier", category: "verbes", hsk: 1, sentences: ["我学习中文。"] },
  { id: 98, hanzi: "打电话", pinyin: "dǎ diàn huà", meaning: "Téléphoner", category: "verbes", hsk: 1, sentences: ["我打电话给妈妈。"] },
  { id: 99, hanzi: "下雨", pinyin: "xià yǔ", meaning: "Pleuvoir", category: "verbes", hsk: 1, sentences: ["今天下雨了。"] },

  // === ADJECTIFS (adjectives) ===
  { id: 100, hanzi: "好", pinyin: "hǎo", meaning: "Bon / Bien", category: "adjectifs", hsk: 1, sentences: ["这个很好。"] },
  { id: 101, hanzi: "大", pinyin: "dà", meaning: "Grand", category: "adjectifs", hsk: 1, sentences: ["这个学校很大。"] },
  { id: 102, hanzi: "小", pinyin: "xiǎo", meaning: "Petit", category: "adjectifs", hsk: 1, sentences: ["小猫很可爱。"] },
  { id: 103, hanzi: "多", pinyin: "duō", meaning: "Beaucoup", category: "adjectifs", hsk: 1, sentences: ["人很多。"] },
  { id: 104, hanzi: "少", pinyin: "shǎo", meaning: "Peu", category: "adjectifs", hsk: 1, sentences: ["人很少。"] },
  { id: 105, hanzi: "热", pinyin: "rè", meaning: "Chaud", category: "adjectifs", hsk: 1, sentences: ["今天很热。"] },
  { id: 106, hanzi: "冷", pinyin: "lěng", meaning: "Froid", category: "adjectifs", hsk: 1, sentences: ["今天很冷。"] },
  { id: 107, hanzi: "高兴", pinyin: "gāo xìng", meaning: "Content", category: "adjectifs", hsk: 1, sentences: ["我很高兴。"] },
  { id: 108, hanzi: "漂亮", pinyin: "piào liang", meaning: "Joli / Beau", category: "adjectifs", hsk: 1, sentences: ["她很漂亮。"] },
  { id: 109, hanzi: "高", pinyin: "gāo", meaning: "Grand (taille)", category: "adjectifs", hsk: 1, sentences: ["他很高。"] },

  // === LIEUX (places) ===
  { id: 110, hanzi: "中国", pinyin: "zhōng guó", meaning: "Chine", category: "lieux", hsk: 1, sentences: ["我去中国。"] },
  { id: 111, hanzi: "北京", pinyin: "běi jīng", meaning: "Pékin", category: "lieux", hsk: 1, sentences: ["我住在北京。"] },
  { id: 112, hanzi: "学校", pinyin: "xué xiào", meaning: "École", category: "lieux", hsk: 1, sentences: ["我去学校。"] },
  { id: 113, hanzi: "医院", pinyin: "yī yuàn", meaning: "Hôpital", category: "lieux", hsk: 1, sentences: ["他在医院。"] },
  { id: 114, hanzi: "商店", pinyin: "shāng diàn", meaning: "Magasin", category: "lieux", hsk: 1, sentences: ["我去商店买东西。"] },
  { id: 115, hanzi: "饭店", pinyin: "fàn diàn", meaning: "Restaurant / Hôtel", category: "lieux", hsk: 1, sentences: ["我们去饭店吃饭。"] },
  { id: 116, hanzi: "火车站", pinyin: "huǒ chē zhàn", meaning: "Gare", category: "lieux", hsk: 1, sentences: ["火车站在哪儿？"] },
  { id: 117, hanzi: "中文", pinyin: "zhōng wén", meaning: "Chinois (langue)", category: "lieux", hsk: 1, sentences: ["我学中文。"] },
  { id: 118, hanzi: "里", pinyin: "lǐ", meaning: "Dans / Dedans", category: "lieux", hsk: 1, sentences: ["书在桌子里。"] },
  { id: 119, hanzi: "上", pinyin: "shàng", meaning: "Sur / Dessus", category: "lieux", hsk: 1, sentences: ["书在桌子上。"] },
  { id: 120, hanzi: "下", pinyin: "xià", meaning: "Sous / Dessous", category: "lieux", hsk: 1, sentences: ["猫在桌子下。"] },
  { id: 121, hanzi: "哪儿", pinyin: "nǎr", meaning: "Où", category: "lieux", hsk: 1, sentences: ["你去哪儿？"] },
  { id: 122, hanzi: "这儿", pinyin: "zhèr", meaning: "Ici", category: "lieux", hsk: 1, sentences: ["请来这儿。"] },

  // === OBJETS (objects) ===
  { id: 123, hanzi: "书", pinyin: "shū", meaning: "Livre", category: "objets", hsk: 1, sentences: ["我有一本书。"] },
  { id: 124, hanzi: "桌子", pinyin: "zhuō zi", meaning: "Table", category: "objets", hsk: 1, sentences: ["书在桌子上。"] },
  { id: 125, hanzi: "椅子", pinyin: "yǐ zi", meaning: "Chaise", category: "objets", hsk: 1, sentences: ["请坐椅子。"] },
  { id: 126, hanzi: "电脑", pinyin: "diàn nǎo", meaning: "Ordinateur", category: "objets", hsk: 1, sentences: ["我用电脑。"] },
  { id: 127, hanzi: "电视", pinyin: "diàn shì", meaning: "Télévision", category: "objets", hsk: 1, sentences: ["我看电视。"] },
  { id: 128, hanzi: "电影", pinyin: "diàn yǐng", meaning: "Film", category: "objets", hsk: 1, sentences: ["我看电影。"] },
  { id: 129, hanzi: "天气", pinyin: "tiān qì", meaning: "Météo / Temps", category: "objets", hsk: 1, sentences: ["今天天气很好。"] },
  { id: 130, hanzi: "猫", pinyin: "māo", meaning: "Chat", category: "objets", hsk: 1, sentences: ["我喜欢猫。"] },
  { id: 131, hanzi: "狗", pinyin: "gǒu", meaning: "Chien", category: "objets", hsk: 1, sentences: ["他有一只狗。"] },
  { id: 132, hanzi: "东西", pinyin: "dōng xi", meaning: "Chose / Objet", category: "objets", hsk: 1, sentences: ["买东西。"] },
  { id: 133, hanzi: "名字", pinyin: "míng zi", meaning: "Nom / Prénom", category: "objets", hsk: 1, sentences: ["你叫什么名字？"] },
  { id: 134, hanzi: "衣服", pinyin: "yī fu", meaning: "Vêtements", category: "objets", hsk: 1, sentences: ["我买衣服。"] },
  { id: 135, hanzi: "飞机", pinyin: "fēi jī", meaning: "Avion", category: "objets", hsk: 1, sentences: ["我坐飞机去中国。"] },
  { id: 136, hanzi: "出租车", pinyin: "chū zū chē", meaning: "Taxi", category: "objets", hsk: 1, sentences: ["我坐出租车。"] },

  // === MOTS OUTILS (function words) ===
  { id: 137, hanzi: "不", pinyin: "bù", meaning: "Non / Ne...pas", category: "outils", hsk: 1, sentences: ["我不去。"] },
  { id: 138, hanzi: "没", pinyin: "méi", meaning: "Ne...pas (passé)", category: "outils", hsk: 1, sentences: ["我没有钱。"] },
  { id: 139, hanzi: "很", pinyin: "hěn", meaning: "Très", category: "outils", hsk: 1, sentences: ["很好！"] },
  { id: 140, hanzi: "也", pinyin: "yě", meaning: "Aussi", category: "outils", hsk: 1, sentences: ["我也是学生。"] },
  { id: 141, hanzi: "都", pinyin: "dōu", meaning: "Tous / Tout", category: "outils", hsk: 1, sentences: ["我们都是学生。"] },
  { id: 142, hanzi: "的", pinyin: "de", meaning: "De (possession)", category: "outils", hsk: 1, sentences: ["我的书。"] },
  { id: 143, hanzi: "了", pinyin: "le", meaning: "Particule (accompli)", category: "outils", hsk: 1, sentences: ["我吃了。"] },
  { id: 144, hanzi: "和", pinyin: "hé", meaning: "Et", category: "outils", hsk: 1, sentences: ["我和你。"] },
  { id: 145, hanzi: "吗", pinyin: "ma", meaning: "Particule (question)", category: "outils", hsk: 1, sentences: ["你好吗？"] },
  { id: 146, hanzi: "呢", pinyin: "ne", meaning: "Particule (et toi ?)", category: "outils", hsk: 1, sentences: ["你呢？"] },
  { id: 147, hanzi: "什么", pinyin: "shén me", meaning: "Quoi / Quel", category: "outils", hsk: 1, sentences: ["这是什么？"] },
  { id: 148, hanzi: "谁", pinyin: "shéi", meaning: "Qui", category: "outils", hsk: 1, sentences: ["你是谁？"] },
  { id: 149, hanzi: "怎么", pinyin: "zěn me", meaning: "Comment", category: "outils", hsk: 1, sentences: ["怎么去？"] },
  { id: 150, hanzi: "怎么样", pinyin: "zěn me yàng", meaning: "Comment (opinion)", category: "outils", hsk: 1, sentences: ["今天怎么样？"] },

  // === MÉTIERS & RÔLES ===
  { id: 151, hanzi: "学生", pinyin: "xué sheng", meaning: "Étudiant", category: "metiers", hsk: 1, sentences: ["我是学生。"] },
  { id: 152, hanzi: "老师", pinyin: "lǎo shī", meaning: "Professeur", category: "metiers", hsk: 1, sentences: ["她是老师。"] },
  { id: 153, hanzi: "医生", pinyin: "yī shēng", meaning: "Médecin", category: "metiers", hsk: 1, sentences: ["爸爸是医生。"] },
  { id: 154, hanzi: "本", pinyin: "běn", meaning: "Classif. livres", category: "outils", hsk: 1, sentences: ["一本书。"] },
  { id: 155, hanzi: "些", pinyin: "xiē", meaning: "Quelques", category: "outils", hsk: 1, sentences: ["一些人。"] },
  { id: 156, hanzi: "太", pinyin: "tài", meaning: "Trop", category: "outils", hsk: 1, sentences: ["太好了！"] },

  // =============================================
  // HSK 2 (~150 words, ids 157–306)
  // =============================================

  // === HSK2 — FAMILLE ===
  { id: 157, hanzi: "哥哥", pinyin: "gēge", meaning: "Frère aîné", category: "famille", hsk: 2, sentences: ["我哥哥比我高。"] },
  { id: 158, hanzi: "姐姐", pinyin: "jiějie", meaning: "Sœur aînée", category: "famille", hsk: 2, sentences: ["姐姐在大学学习。"] },
  { id: 159, hanzi: "弟弟", pinyin: "dìdi", meaning: "Frère cadet", category: "famille", hsk: 2, sentences: ["弟弟今年十岁。"] },
  { id: 160, hanzi: "妹妹", pinyin: "mèimei", meaning: "Sœur cadette", category: "famille", hsk: 2, sentences: ["妹妹喜欢画画。"] },
  { id: 161, hanzi: "丈夫", pinyin: "zhàngfu", meaning: "Mari", category: "famille", hsk: 2, sentences: ["她的丈夫是老师。"] },
  { id: 162, hanzi: "妻子", pinyin: "qīzi", meaning: "Épouse", category: "famille", hsk: 2, sentences: ["他的妻子很漂亮。"] },
  { id: 163, hanzi: "孩子", pinyin: "háizi", meaning: "Enfant", category: "famille", hsk: 2, sentences: ["孩子们在玩。"] },
  { id: 164, hanzi: "奶奶", pinyin: "nǎinai", meaning: "Grand-mère paternelle", category: "famille", hsk: 2, sentences: ["奶奶做的菜很好吃。"] },
  { id: 165, hanzi: "爷爷", pinyin: "yéye", meaning: "Grand-père paternel", category: "famille", hsk: 2, sentences: ["爷爷每天早上锻炼。"] },
  { id: 166, hanzi: "女人", pinyin: "nǚrén", meaning: "Femme", category: "famille", hsk: 2, sentences: ["那个女人是谁？"] },
  { id: 167, hanzi: "男人", pinyin: "nánrén", meaning: "Homme", category: "famille", hsk: 2, sentences: ["那个男人很高。"] },
  { id: 168, hanzi: "别人", pinyin: "biérén", meaning: "Les autres", category: "famille", hsk: 2, sentences: ["不要管别人的事。"] },

  // === HSK2 — NOURRITURE ===
  { id: 169, hanzi: "鸡蛋", pinyin: "jīdàn", meaning: "Œuf", category: "nourriture", hsk: 2, sentences: ["我早上吃了两个鸡蛋。"] },
  { id: 170, hanzi: "面条", pinyin: "miàntiáo", meaning: "Nouilles", category: "nourriture", hsk: 2, sentences: ["我喜欢吃面条。"] },
  { id: 171, hanzi: "牛奶", pinyin: "niúnǎi", meaning: "Lait", category: "nourriture", hsk: 2, sentences: ["每天喝一杯牛奶。"] },
  { id: 172, hanzi: "西瓜", pinyin: "xīguā", meaning: "Pastèque", category: "nourriture", hsk: 2, sentences: ["夏天吃西瓜很好。"] },
  { id: 173, hanzi: "鱼", pinyin: "yú", meaning: "Poisson", category: "nourriture", hsk: 2, sentences: ["这条鱼很新鲜。"] },
  { id: 174, hanzi: "羊肉", pinyin: "yángròu", meaning: "Mouton (viande)", category: "nourriture", hsk: 2, sentences: ["冬天吃羊肉很暖和。"] },
  { id: 175, hanzi: "啤酒", pinyin: "píjiǔ", meaning: "Bière", category: "nourriture", hsk: 2, sentences: ["你想喝啤酒吗？"] },
  { id: 176, hanzi: "咖啡", pinyin: "kāfēi", meaning: "Café", category: "nourriture", hsk: 2, sentences: ["我每天喝一杯咖啡。"] },
  { id: 177, hanzi: "面包", pinyin: "miànbāo", meaning: "Pain", category: "nourriture", hsk: 2, sentences: ["早上吃面包和牛奶。"] },
  { id: 178, hanzi: "饺子", pinyin: "jiǎozi", meaning: "Raviolis", category: "nourriture", hsk: 2, sentences: ["过年要吃饺子。"] },
  { id: 179, hanzi: "蛋糕", pinyin: "dàngāo", meaning: "Gâteau", category: "nourriture", hsk: 2, sentences: ["生日蛋糕很好吃。"] },
  { id: 180, hanzi: "香蕉", pinyin: "xiāngjiāo", meaning: "Banane", category: "nourriture", hsk: 2, sentences: ["我买了几根香蕉。"] },

  // === HSK2 — TEMPS ===
  { id: 181, hanzi: "早上", pinyin: "zǎoshang", meaning: "Matin", category: "temps", hsk: 2, sentences: ["早上好！"] },
  { id: 182, hanzi: "晚上", pinyin: "wǎnshang", meaning: "Soir", category: "temps", hsk: 2, sentences: ["晚上我在家看书。"] },
  { id: 183, hanzi: "小时", pinyin: "xiǎoshí", meaning: "Heure (durée)", category: "temps", hsk: 2, sentences: ["我学了两个小时。"] },
  { id: 184, hanzi: "去年", pinyin: "qùnián", meaning: "L'année dernière", category: "temps", hsk: 2, sentences: ["去年我去了中国。"] },
  { id: 185, hanzi: "生日", pinyin: "shēngrì", meaning: "Anniversaire", category: "temps", hsk: 2, sentences: ["今天是我的生日。"] },
  { id: 186, hanzi: "最近", pinyin: "zuìjìn", meaning: "Récemment", category: "temps", hsk: 2, sentences: ["最近你怎么样？"] },
  { id: 187, hanzi: "已经", pinyin: "yǐjīng", meaning: "Déjà", category: "temps", hsk: 2, sentences: ["我已经吃了。"] },
  { id: 188, hanzi: "一直", pinyin: "yìzhí", meaning: "Toujours/tout le temps", category: "temps", hsk: 2, sentences: ["他一直在学习。"] },
  { id: 189, hanzi: "马上", pinyin: "mǎshàng", meaning: "Tout de suite", category: "temps", hsk: 2, sentences: ["我马上就来。"] },
  { id: 190, hanzi: "以前", pinyin: "yǐqián", meaning: "Avant/autrefois", category: "temps", hsk: 2, sentences: ["以前我住在上海。"] },
  { id: 191, hanzi: "以后", pinyin: "yǐhòu", meaning: "Après/plus tard", category: "temps", hsk: 2, sentences: ["以后我想去法国。"] },
  { id: 192, hanzi: "每天", pinyin: "měitiān", meaning: "Chaque jour", category: "temps", hsk: 2, sentences: ["我每天早上跑步。"] },

  // === HSK2 — VERBES ===
  { id: 193, hanzi: "帮助", pinyin: "bāngzhù", meaning: "Aider", category: "verbes", hsk: 2, sentences: ["谢谢你帮助我。"] },
  { id: 194, hanzi: "准备", pinyin: "zhǔnbèi", meaning: "Préparer", category: "verbes", hsk: 2, sentences: ["我在准备考试。"] },
  { id: 195, hanzi: "开始", pinyin: "kāishǐ", meaning: "Commencer", category: "verbes", hsk: 2, sentences: ["上课开始了。"] },
  { id: 196, hanzi: "完成", pinyin: "wánchéng", meaning: "Terminer", category: "verbes", hsk: 2, sentences: ["我完成了作业。"] },
  { id: 197, hanzi: "告诉", pinyin: "gàosu", meaning: "Dire/informer", category: "verbes", hsk: 2, sentences: ["请告诉我你的名字。"] },
  { id: 198, hanzi: "觉得", pinyin: "juéde", meaning: "Penser/trouver que", category: "verbes", hsk: 2, sentences: ["我觉得中文很有趣。"] },
  { id: 199, hanzi: "希望", pinyin: "xīwàng", meaning: "Espérer", category: "verbes", hsk: 2, sentences: ["我希望明天不下雨。"] },
  { id: 200, hanzi: "让", pinyin: "ràng", meaning: "Laisser/permettre", category: "verbes", hsk: 2, sentences: ["妈妈让我去买东西。"] },
  { id: 201, hanzi: "送", pinyin: "sòng", meaning: "Offrir/accompagner", category: "verbes", hsk: 2, sentences: ["我送你一个礼物。"] },
  { id: 202, hanzi: "找", pinyin: "zhǎo", meaning: "Chercher", category: "verbes", hsk: 2, sentences: ["我在找我的钥匙。"] },
  { id: 203, hanzi: "玩", pinyin: "wán", meaning: "Jouer/s'amuser", category: "verbes", hsk: 2, sentences: ["孩子们在外面玩。"] },
  { id: 204, hanzi: "跑", pinyin: "pǎo", meaning: "Courir", category: "verbes", hsk: 2, sentences: ["他跑得很快。"] },
  { id: 205, hanzi: "走", pinyin: "zǒu", meaning: "Marcher/partir", category: "verbes", hsk: 2, sentences: ["我们走吧。"] },
  { id: 206, hanzi: "等", pinyin: "děng", meaning: "Attendre", category: "verbes", hsk: 2, sentences: ["请等一下。"] },
  { id: 207, hanzi: "唱歌", pinyin: "chànggē", meaning: "Chanter", category: "verbes", hsk: 2, sentences: ["她喜欢唱歌。"] },
  { id: 208, hanzi: "跳舞", pinyin: "tiàowǔ", meaning: "Danser", category: "verbes", hsk: 2, sentences: ["他们在跳舞。"] },
  { id: 209, hanzi: "考试", pinyin: "kǎoshì", meaning: "Passer un examen", category: "verbes", hsk: 2, sentences: ["明天有考试。"] },
  { id: 210, hanzi: "锻炼", pinyin: "duànliàn", meaning: "Faire du sport", category: "verbes", hsk: 2, sentences: ["我每天锻炼身体。"] },
  { id: 211, hanzi: "旅游", pinyin: "lǚyóu", meaning: "Voyager", category: "verbes", hsk: 2, sentences: ["我喜欢去旅游。"] },
  { id: 212, hanzi: "上班", pinyin: "shàngbān", meaning: "Aller au travail", category: "verbes", hsk: 2, sentences: ["爸爸每天上班。"] },
  { id: 213, hanzi: "生病", pinyin: "shēngbìng", meaning: "Être malade", category: "verbes", hsk: 2, sentences: ["他生病了，不能来。"] },
  { id: 214, hanzi: "结婚", pinyin: "jiéhūn", meaning: "Se marier", category: "verbes", hsk: 2, sentences: ["他们去年结婚了。"] },
  { id: 215, hanzi: "离开", pinyin: "líkāi", meaning: "Quitter", category: "verbes", hsk: 2, sentences: ["他离开了北京。"] },
  { id: 216, hanzi: "迟到", pinyin: "chídào", meaning: "Être en retard", category: "verbes", hsk: 2, sentences: ["对不起，我迟到了。"] },
  { id: 217, hanzi: "游泳", pinyin: "yóuyǒng", meaning: "Nager", category: "verbes", hsk: 2, sentences: ["夏天我喜欢游泳。"] },

  // === HSK2 — OBJETS ===
  { id: 218, hanzi: "手机", pinyin: "shǒujī", meaning: "Téléphone portable", category: "objets", hsk: 2, sentences: ["我的手机在桌子上。"] },
  { id: 219, hanzi: "手表", pinyin: "shǒubiǎo", meaning: "Montre", category: "objets", hsk: 2, sentences: ["这块手表很贵。"] },
  { id: 220, hanzi: "自行车", pinyin: "zìxíngchē", meaning: "Vélo", category: "objets", hsk: 2, sentences: ["我骑自行车去学校。"] },
  { id: 221, hanzi: "公共汽车", pinyin: "gōnggòngqìchē", meaning: "Bus", category: "objets", hsk: 2, sentences: ["我坐公共汽车去上班。"] },
  { id: 222, hanzi: "地铁", pinyin: "dìtiě", meaning: "Métro", category: "objets", hsk: 2, sentences: ["坐地铁很方便。"] },
  { id: 223, hanzi: "眼镜", pinyin: "yǎnjìng", meaning: "Lunettes", category: "objets", hsk: 2, sentences: ["他戴眼镜。"] },
  { id: 224, hanzi: "照片", pinyin: "zhàopiàn", meaning: "Photo", category: "objets", hsk: 2, sentences: ["这张照片很好看。"] },
  { id: 225, hanzi: "新闻", pinyin: "xīnwén", meaning: "Nouvelles", category: "objets", hsk: 2, sentences: ["你看新闻了吗？"] },
  { id: 226, hanzi: "问题", pinyin: "wèntí", meaning: "Question/problème", category: "objets", hsk: 2, sentences: ["我有一个问题。"] },
  { id: 227, hanzi: "铅笔", pinyin: "qiānbǐ", meaning: "Crayon", category: "objets", hsk: 2, sentences: ["请给我一支铅笔。"] },
  { id: 228, hanzi: "作业", pinyin: "zuòyè", meaning: "Devoirs", category: "objets", hsk: 2, sentences: ["我在做作业。"] },
  { id: 229, hanzi: "报纸", pinyin: "bàozhǐ", meaning: "Journal", category: "objets", hsk: 2, sentences: ["爷爷在看报纸。"] },
  { id: 230, hanzi: "字典", pinyin: "zìdiǎn", meaning: "Dictionnaire", category: "objets", hsk: 2, sentences: ["我用字典查这个字。"] },
  { id: 231, hanzi: "护照", pinyin: "hùzhào", meaning: "Passeport", category: "objets", hsk: 2, sentences: ["请出示你的护照。"] },
  { id: 232, hanzi: "地图", pinyin: "dìtú", meaning: "Carte", category: "objets", hsk: 2, sentences: ["我看地图找路。"] },

  // === HSK2 — LIEUX ===
  { id: 233, hanzi: "超市", pinyin: "chāoshì", meaning: "Supermarché", category: "lieux", hsk: 2, sentences: ["我去超市买东西。"] },
  { id: 234, hanzi: "银行", pinyin: "yínháng", meaning: "Banque", category: "lieux", hsk: 2, sentences: ["银行在哪儿？"] },
  { id: 235, hanzi: "公园", pinyin: "gōngyuán", meaning: "Parc", category: "lieux", hsk: 2, sentences: ["我们去公园走走。"] },
  { id: 236, hanzi: "图书馆", pinyin: "túshūguǎn", meaning: "Bibliothèque", category: "lieux", hsk: 2, sentences: ["图书馆里很安静。"] },
  { id: 237, hanzi: "机场", pinyin: "jīchǎng", meaning: "Aéroport", category: "lieux", hsk: 2, sentences: ["我去机场接朋友。"] },
  { id: 238, hanzi: "教室", pinyin: "jiàoshì", meaning: "Salle de classe", category: "lieux", hsk: 2, sentences: ["学生们在教室里。"] },
  { id: 239, hanzi: "办公室", pinyin: "bàngōngshì", meaning: "Bureau (pièce)", category: "lieux", hsk: 2, sentences: ["老师在办公室。"] },
  { id: 240, hanzi: "厨房", pinyin: "chúfáng", meaning: "Cuisine (pièce)", category: "lieux", hsk: 2, sentences: ["妈妈在厨房做饭。"] },
  { id: 241, hanzi: "卫生间", pinyin: "wèishēngjiān", meaning: "Toilettes", category: "lieux", hsk: 2, sentences: ["卫生间在哪儿？"] },
  { id: 242, hanzi: "门", pinyin: "mén", meaning: "Porte", category: "lieux", hsk: 2, sentences: ["请关门。"] },
  { id: 243, hanzi: "窗户", pinyin: "chuānghu", meaning: "Fenêtre", category: "lieux", hsk: 2, sentences: ["请打开窗户。"] },
  { id: 244, hanzi: "楼", pinyin: "lóu", meaning: "Immeuble/étage", category: "lieux", hsk: 2, sentences: ["我住在三楼。"] },
  { id: 245, hanzi: "左边", pinyin: "zuǒbian", meaning: "Gauche", category: "lieux", hsk: 2, sentences: ["银行在左边。"] },
  { id: 246, hanzi: "右边", pinyin: "yòubian", meaning: "Droite", category: "lieux", hsk: 2, sentences: ["超市在右边。"] },
  { id: 247, hanzi: "旁边", pinyin: "pángbiān", meaning: "À côté", category: "lieux", hsk: 2, sentences: ["学校旁边有一家商店。"] },

  // === HSK2 — ADJECTIFS ===
  { id: 248, hanzi: "便宜", pinyin: "piányi", meaning: "Bon marché", category: "adjectifs", hsk: 2, sentences: ["这个东西很便宜。"] },
  { id: 249, hanzi: "贵", pinyin: "guì", meaning: "Cher (prix)", category: "adjectifs", hsk: 2, sentences: ["这件衣服太贵了。"] },
  { id: 250, hanzi: "新", pinyin: "xīn", meaning: "Nouveau", category: "adjectifs", hsk: 2, sentences: ["我买了一件新衣服。"] },
  { id: 251, hanzi: "旧", pinyin: "jiù", meaning: "Ancien/vieux", category: "adjectifs", hsk: 2, sentences: ["这本书很旧了。"] },
  { id: 252, hanzi: "快", pinyin: "kuài", meaning: "Rapide", category: "adjectifs", hsk: 2, sentences: ["他跑得很快。"] },
  { id: 253, hanzi: "慢", pinyin: "màn", meaning: "Lent", category: "adjectifs", hsk: 2, sentences: ["请说慢一点。"] },
  { id: 254, hanzi: "近", pinyin: "jìn", meaning: "Proche", category: "adjectifs", hsk: 2, sentences: ["学校离我家很近。"] },
  { id: 255, hanzi: "远", pinyin: "yuǎn", meaning: "Loin", category: "adjectifs", hsk: 2, sentences: ["机场很远。"] },
  { id: 256, hanzi: "长", pinyin: "cháng", meaning: "Long", category: "adjectifs", hsk: 2, sentences: ["这条路很长。"] },
  { id: 257, hanzi: "短", pinyin: "duǎn", meaning: "Court", category: "adjectifs", hsk: 2, sentences: ["时间很短。"] },
  { id: 258, hanzi: "难", pinyin: "nán", meaning: "Difficile", category: "adjectifs", hsk: 2, sentences: ["中文很难吗？"] },
  { id: 259, hanzi: "容易", pinyin: "róngyì", meaning: "Facile", category: "adjectifs", hsk: 2, sentences: ["这个很容易。"] },
  { id: 260, hanzi: "重要", pinyin: "zhòngyào", meaning: "Important", category: "adjectifs", hsk: 2, sentences: ["这件事很重要。"] },
  { id: 261, hanzi: "忙", pinyin: "máng", meaning: "Occupé", category: "adjectifs", hsk: 2, sentences: ["你最近忙吗？"] },
  { id: 262, hanzi: "累", pinyin: "lèi", meaning: "Fatigué", category: "adjectifs", hsk: 2, sentences: ["今天我很累。"] },

  // === HSK2 — OUTILS ===
  { id: 263, hanzi: "因为", pinyin: "yīnwèi", meaning: "Parce que", category: "outils", hsk: 2, sentences: ["因为下雨，我没去。"] },
  { id: 264, hanzi: "所以", pinyin: "suǒyǐ", meaning: "Donc", category: "outils", hsk: 2, sentences: ["我累了，所以休息。"] },
  { id: 265, hanzi: "如果", pinyin: "rúguǒ", meaning: "Si (condition)", category: "outils", hsk: 2, sentences: ["如果明天不下雨，我们去公园。"] },
  { id: 266, hanzi: "虽然", pinyin: "suīrán", meaning: "Bien que", category: "outils", hsk: 2, sentences: ["虽然很难，但是我想学。"] },
  { id: 267, hanzi: "但是", pinyin: "dànshì", meaning: "Mais", category: "outils", hsk: 2, sentences: ["我想去，但是没时间。"] },
  { id: 268, hanzi: "或者", pinyin: "huòzhě", meaning: "Ou bien", category: "outils", hsk: 2, sentences: ["你喝茶或者咖啡？"] },
  { id: 269, hanzi: "还是", pinyin: "háishi", meaning: "Ou bien (question)", category: "outils", hsk: 2, sentences: ["你吃米饭还是面条？"] },
  { id: 270, hanzi: "比", pinyin: "bǐ", meaning: "Comparé à", category: "outils", hsk: 2, sentences: ["他比我高。"] },
  { id: 271, hanzi: "最", pinyin: "zuì", meaning: "Le plus", category: "outils", hsk: 2, sentences: ["他是最好的学生。"] },
  { id: 272, hanzi: "更", pinyin: "gèng", meaning: "Plus/encore plus", category: "outils", hsk: 2, sentences: ["今天更冷了。"] },
  { id: 273, hanzi: "非常", pinyin: "fēicháng", meaning: "Très/extrêmement", category: "outils", hsk: 2, sentences: ["这个菜非常好吃。"] },
  { id: 274, hanzi: "真", pinyin: "zhēn", meaning: "Vraiment", category: "outils", hsk: 2, sentences: ["你真好！"] },
  { id: 275, hanzi: "应该", pinyin: "yīnggāi", meaning: "Devoir", category: "outils", hsk: 2, sentences: ["你应该多休息。"] },
  { id: 276, hanzi: "可能", pinyin: "kěnéng", meaning: "Possible/peut-être", category: "outils", hsk: 2, sentences: ["明天可能下雨。"] },
  { id: 277, hanzi: "当然", pinyin: "dāngrán", meaning: "Bien sûr", category: "outils", hsk: 2, sentences: ["当然可以！"] },

  // === HSK2 — MÉTIERS ===
  { id: 278, hanzi: "经理", pinyin: "jīnglǐ", meaning: "Directeur/gérant", category: "metiers", hsk: 2, sentences: ["他是公司的经理。"] },
  { id: 279, hanzi: "司机", pinyin: "sījī", meaning: "Chauffeur", category: "metiers", hsk: 2, sentences: ["司机开车很小心。"] },
  { id: 280, hanzi: "护士", pinyin: "hùshi", meaning: "Infirmier/ère", category: "metiers", hsk: 2, sentences: ["护士照顾病人。"] },
  { id: 281, hanzi: "服务员", pinyin: "fúwùyuán", meaning: "Serveur/euse", category: "metiers", hsk: 2, sentences: ["服务员，买单！"] },
  { id: 282, hanzi: "警察", pinyin: "jǐngchá", meaning: "Policier", category: "metiers", hsk: 2, sentences: ["警察在路口。"] },
  { id: 283, hanzi: "记者", pinyin: "jìzhě", meaning: "Journaliste", category: "metiers", hsk: 2, sentences: ["他是一名记者。"] },
  { id: 284, hanzi: "演员", pinyin: "yǎnyuán", meaning: "Acteur/actrice", category: "metiers", hsk: 2, sentences: ["她是有名的演员。"] },
  { id: 285, hanzi: "运动员", pinyin: "yùndòngyuán", meaning: "Athlète", category: "metiers", hsk: 2, sentences: ["他是一名运动员。"] },

  // === HSK2 — NATURE ===
  { id: 286, hanzi: "花", pinyin: "huā", meaning: "Fleur", category: "nature", hsk: 2, sentences: ["这朵花很漂亮。"] },
  { id: 287, hanzi: "树", pinyin: "shù", meaning: "Arbre", category: "nature", hsk: 2, sentences: ["公园里有很多树。"] },
  { id: 288, hanzi: "山", pinyin: "shān", meaning: "Montagne", category: "nature", hsk: 2, sentences: ["那座山很高。"] },
  { id: 289, hanzi: "河", pinyin: "hé", meaning: "Rivière", category: "nature", hsk: 2, sentences: ["河里有鱼。"] },
  { id: 290, hanzi: "雪", pinyin: "xuě", meaning: "Neige", category: "nature", hsk: 2, sentences: ["冬天下雪了。"] },
  { id: 291, hanzi: "风", pinyin: "fēng", meaning: "Vent", category: "nature", hsk: 2, sentences: ["今天风很大。"] },
  { id: 292, hanzi: "云", pinyin: "yún", meaning: "Nuage", category: "nature", hsk: 2, sentences: ["天上有很多云。"] },
  { id: 293, hanzi: "太阳", pinyin: "tàiyáng", meaning: "Soleil", category: "nature", hsk: 2, sentences: ["太阳出来了。"] },

  // === HSK2 — ANIMAUX ===
  { id: 294, hanzi: "鸟", pinyin: "niǎo", meaning: "Oiseau", category: "animaux", hsk: 2, sentences: ["树上有一只鸟。"] },
  { id: 295, hanzi: "马", pinyin: "mǎ", meaning: "Cheval", category: "animaux", hsk: 2, sentences: ["他会骑马。"] },
  { id: 296, hanzi: "鸡", pinyin: "jī", meaning: "Poule/poulet", category: "animaux", hsk: 2, sentences: ["我家养了几只鸡。"] },
  { id: 297, hanzi: "羊", pinyin: "yáng", meaning: "Mouton", category: "animaux", hsk: 2, sentences: ["山上有一群羊。"] },
  { id: 298, hanzi: "牛", pinyin: "niú", meaning: "Bœuf/vache", category: "animaux", hsk: 2, sentences: ["农民养了一头牛。"] },
  { id: 299, hanzi: "兔子", pinyin: "tùzi", meaning: "Lapin", category: "animaux", hsk: 2, sentences: ["兔子跑得很快。"] },
  { id: 300, hanzi: "熊猫", pinyin: "xióngmāo", meaning: "Panda", category: "animaux", hsk: 2, sentences: ["熊猫是中国的国宝。"] },

  // === HSK2 — CORPS ===
  { id: 301, hanzi: "头", pinyin: "tóu", meaning: "Tête", category: "corps", hsk: 2, sentences: ["我头疼。"] },
  { id: 302, hanzi: "眼睛", pinyin: "yǎnjing", meaning: "Yeux", category: "corps", hsk: 2, sentences: ["她的眼睛很大。"] },
  { id: 303, hanzi: "耳朵", pinyin: "ěrduo", meaning: "Oreilles", category: "corps", hsk: 2, sentences: ["兔子的耳朵很长。"] },
  { id: 304, hanzi: "嘴", pinyin: "zuǐ", meaning: "Bouche", category: "corps", hsk: 2, sentences: ["请张开嘴。"] },
  { id: 305, hanzi: "鼻子", pinyin: "bízi", meaning: "Nez", category: "corps", hsk: 2, sentences: ["他的鼻子很高。"] },
  { id: 306, hanzi: "手", pinyin: "shǒu", meaning: "Main", category: "corps", hsk: 2, sentences: ["请洗手。"] },
  { id: 307, hanzi: "脚", pinyin: "jiǎo", meaning: "Pied", category: "corps", hsk: 2, sentences: ["我的脚很疼。"] },
  { id: 308, hanzi: "身体", pinyin: "shēntǐ", meaning: "Corps", category: "corps", hsk: 2, sentences: ["身体健康很重要。"] },

  // =============================================
  // HSK 3 (~300 words, ids 309–608)
  // =============================================

  // === HSK3 — FAMILLE ===
  { id: 309, hanzi: "父亲", pinyin: "fùqīn", meaning: "Père", category: "famille", hsk: 3, sentences: ["我父亲是工程师。"] },
  { id: 310, hanzi: "母亲", pinyin: "mǔqīn", meaning: "Mère", category: "famille", hsk: 3, sentences: ["母亲每天很辛苦。"] },
  { id: 311, hanzi: "叔叔", pinyin: "shūshu", meaning: "Oncle (paternel)", category: "famille", hsk: 3, sentences: ["叔叔住在上海。"] },
  { id: 312, hanzi: "阿姨", pinyin: "āyí", meaning: "Tante", category: "famille", hsk: 3, sentences: ["阿姨做的菜很好吃。"] },
  { id: 313, hanzi: "邻居", pinyin: "línjū", meaning: "Voisin", category: "famille", hsk: 3, sentences: ["我的邻居很友好。"] },
  { id: 314, hanzi: "客人", pinyin: "kèrén", meaning: "Invité", category: "famille", hsk: 3, sentences: ["家里来了客人。"] },
  { id: 315, hanzi: "亲戚", pinyin: "qīnqi", meaning: "Parent (famille)", category: "famille", hsk: 3, sentences: ["过年的时候我们去看亲戚。"] },
  { id: 316, hanzi: "对象", pinyin: "duìxiàng", meaning: "Partenaire", category: "famille", hsk: 3, sentences: ["你有对象了吗？"] },
  { id: 317, hanzi: "关系", pinyin: "guānxi", meaning: "Relation", category: "famille", hsk: 3, sentences: ["他们的关系很好。"] },
  { id: 318, hanzi: "约会", pinyin: "yuēhuì", meaning: "Rendez-vous", category: "famille", hsk: 3, sentences: ["他们今天有约会。"] },
  { id: 319, hanzi: "聊天", pinyin: "liáotiān", meaning: "Discuter", category: "famille", hsk: 3, sentences: ["我们一起聊天吧。"] },
  { id: 320, hanzi: "打招呼", pinyin: "dǎzhāohu", meaning: "Saluer", category: "famille", hsk: 3, sentences: ["见面要打招呼。"] },
  { id: 321, hanzi: "国际", pinyin: "guójì", meaning: "International", category: "famille", hsk: 3, sentences: ["这是一所国际学校。"] },
  { id: 322, hanzi: "社会", pinyin: "shèhuì", meaning: "Société", category: "famille", hsk: 3, sentences: ["社会在不断变化。"] },
  { id: 323, hanzi: "世界", pinyin: "shìjiè", meaning: "Monde", category: "famille", hsk: 3, sentences: ["世界很大。"] },

  // === HSK3 — NOURRITURE ===
  { id: 324, hanzi: "葡萄", pinyin: "pútao", meaning: "Raisin", category: "nourriture", hsk: 3, sentences: ["这些葡萄很甜。"] },
  { id: 325, hanzi: "草莓", pinyin: "cǎoméi", meaning: "Fraise", category: "nourriture", hsk: 3, sentences: ["我喜欢吃草莓。"] },
  { id: 326, hanzi: "橘子", pinyin: "júzi", meaning: "Orange (fruit)", category: "nourriture", hsk: 3, sentences: ["给我一个橘子。"] },
  { id: 327, hanzi: "桃子", pinyin: "táozi", meaning: "Pêche", category: "nourriture", hsk: 3, sentences: ["桃子很好吃。"] },
  { id: 328, hanzi: "梨", pinyin: "lí", meaning: "Poire", category: "nourriture", hsk: 3, sentences: ["这个梨很甜。"] },
  { id: 329, hanzi: "蔬菜", pinyin: "shūcài", meaning: "Légumes", category: "nourriture", hsk: 3, sentences: ["多吃蔬菜对身体好。"] },
  { id: 330, hanzi: "土豆", pinyin: "tǔdòu", meaning: "Pomme de terre", category: "nourriture", hsk: 3, sentences: ["我喜欢吃土豆。"] },
  { id: 331, hanzi: "豆腐", pinyin: "dòufu", meaning: "Tofu", category: "nourriture", hsk: 3, sentences: ["豆腐是很健康的食物。"] },
  { id: 332, hanzi: "猪肉", pinyin: "zhūròu", meaning: "Porc", category: "nourriture", hsk: 3, sentences: ["中国人常吃猪肉。"] },
  { id: 333, hanzi: "牛肉", pinyin: "niúròu", meaning: "Bœuf", category: "nourriture", hsk: 3, sentences: ["牛肉面很好吃。"] },
  { id: 334, hanzi: "鸡肉", pinyin: "jīròu", meaning: "Poulet (viande)", category: "nourriture", hsk: 3, sentences: ["鸡肉比牛肉便宜。"] },
  { id: 335, hanzi: "汤", pinyin: "tāng", meaning: "Soupe", category: "nourriture", hsk: 3, sentences: ["妈妈做了一碗汤。"] },
  { id: 336, hanzi: "糖", pinyin: "táng", meaning: "Sucre", category: "nourriture", hsk: 3, sentences: ["咖啡里加糖吗？"] },
  { id: 337, hanzi: "盐", pinyin: "yán", meaning: "Sel", category: "nourriture", hsk: 3, sentences: ["菜里盐放多了。"] },
  { id: 338, hanzi: "醋", pinyin: "cù", meaning: "Vinaigre", category: "nourriture", hsk: 3, sentences: ["吃饺子要蘸醋。"] },
  { id: 339, hanzi: "酱油", pinyin: "jiàngyóu", meaning: "Sauce soja", category: "nourriture", hsk: 3, sentences: ["做菜要放酱油。"] },
  { id: 340, hanzi: "味道", pinyin: "wèidao", meaning: "Goût", category: "nourriture", hsk: 3, sentences: ["这道菜的味道很好。"] },
  { id: 341, hanzi: "饱", pinyin: "bǎo", meaning: "Rassasié", category: "nourriture", hsk: 3, sentences: ["我吃饱了。"] },
  { id: 342, hanzi: "饿", pinyin: "è", meaning: "Affamé", category: "nourriture", hsk: 3, sentences: ["我饿了，想吃饭。"] },
  { id: 343, hanzi: "渴", pinyin: "kě", meaning: "Avoir soif", category: "nourriture", hsk: 3, sentences: ["我渴了，想喝水。"] },

  // === HSK3 — TEMPS ===
  { id: 344, hanzi: "春天", pinyin: "chūntiān", meaning: "Printemps", category: "temps", hsk: 3, sentences: ["春天花开了。"] },
  { id: 345, hanzi: "夏天", pinyin: "xiàtiān", meaning: "Été", category: "temps", hsk: 3, sentences: ["夏天很热。"] },
  { id: 346, hanzi: "秋天", pinyin: "qiūtiān", meaning: "Automne", category: "temps", hsk: 3, sentences: ["秋天叶子变黄了。"] },
  { id: 347, hanzi: "冬天", pinyin: "dōngtiān", meaning: "Hiver", category: "temps", hsk: 3, sentences: ["冬天下雪。"] },
  { id: 348, hanzi: "周末", pinyin: "zhōumò", meaning: "Week-end", category: "temps", hsk: 3, sentences: ["周末你做什么？"] },
  { id: 349, hanzi: "假期", pinyin: "jiàqī", meaning: "Vacances", category: "temps", hsk: 3, sentences: ["假期我去旅游。"] },
  { id: 350, hanzi: "节日", pinyin: "jiérì", meaning: "Fête/festival", category: "temps", hsk: 3, sentences: ["春节是中国最重要的节日。"] },
  { id: 351, hanzi: "将来", pinyin: "jiānglái", meaning: "Futur", category: "temps", hsk: 3, sentences: ["将来我想当老师。"] },
  { id: 352, hanzi: "刚才", pinyin: "gāngcái", meaning: "À l'instant", category: "temps", hsk: 3, sentences: ["刚才谁来了？"] },
  { id: 353, hanzi: "刚", pinyin: "gāng", meaning: "Venir de", category: "temps", hsk: 3, sentences: ["我刚到。"] },
  { id: 354, hanzi: "从来", pinyin: "cónglái", meaning: "Jamais (ne...jamais)", category: "temps", hsk: 3, sentences: ["我从来没去过中国。"] },
  { id: 355, hanzi: "永远", pinyin: "yǒngyuǎn", meaning: "Pour toujours", category: "temps", hsk: 3, sentences: ["我们永远是朋友。"] },
  { id: 356, hanzi: "暂时", pinyin: "zànshí", meaning: "Temporairement", category: "temps", hsk: 3, sentences: ["我暂时住在这里。"] },
  { id: 357, hanzi: "及时", pinyin: "jíshí", meaning: "À temps", category: "temps", hsk: 3, sentences: ["他及时赶到了。"] },
  { id: 358, hanzi: "按时", pinyin: "ànshí", meaning: "À l'heure", category: "temps", hsk: 3, sentences: ["请按时上课。"] },
  { id: 359, hanzi: "世纪", pinyin: "shìjì", meaning: "Siècle", category: "temps", hsk: 3, sentences: ["二十一世纪。"] },
  { id: 360, hanzi: "过去", pinyin: "guòqù", meaning: "Le passé", category: "temps", hsk: 3, sentences: ["过去的事不要再想了。"] },
  { id: 361, hanzi: "未来", pinyin: "wèilái", meaning: "Le futur", category: "temps", hsk: 3, sentences: ["未来会更好。"] },
  { id: 362, hanzi: "半", pinyin: "bàn", meaning: "Moitié", category: "temps", hsk: 3, sentences: ["三点半。"] },
  { id: 363, hanzi: "刻", pinyin: "kè", meaning: "Quart d'heure", category: "temps", hsk: 3, sentences: ["现在三点一刻。"] },
  { id: 364, hanzi: "秒", pinyin: "miǎo", meaning: "Seconde", category: "temps", hsk: 3, sentences: ["请等几秒。"] },
  { id: 365, hanzi: "整", pinyin: "zhěng", meaning: "Entier/pile", category: "temps", hsk: 3, sentences: ["现在八点整。"] },
  { id: 366, hanzi: "上个", pinyin: "shàng gè", meaning: "Le dernier", category: "temps", hsk: 3, sentences: ["上个月我去了北京。"] },
  { id: 367, hanzi: "下个", pinyin: "xià gè", meaning: "Le prochain", category: "temps", hsk: 3, sentences: ["下个星期见。"] },
  { id: 368, hanzi: "日期", pinyin: "rìqī", meaning: "Date", category: "temps", hsk: 3, sentences: ["出发的日期是什么时候？"] },

  // === HSK3 — VERBES ===
  { id: 369, hanzi: "选择", pinyin: "xuǎnzé", meaning: "Choisir", category: "verbes", hsk: 3, sentences: ["你可以选择一个。"] },
  { id: 370, hanzi: "决定", pinyin: "juédìng", meaning: "Décider", category: "verbes", hsk: 3, sentences: ["我决定去中国。"] },
  { id: 371, hanzi: "同意", pinyin: "tóngyì", meaning: "Être d'accord", category: "verbes", hsk: 3, sentences: ["我同意你的意见。"] },
  { id: 372, hanzi: "拒绝", pinyin: "jùjué", meaning: "Refuser", category: "verbes", hsk: 3, sentences: ["他拒绝了我的邀请。"] },
  { id: 373, hanzi: "参加", pinyin: "cānjiā", meaning: "Participer", category: "verbes", hsk: 3, sentences: ["我想参加比赛。"] },
  { id: 374, hanzi: "比赛", pinyin: "bǐsài", meaning: "Compétition", category: "verbes", hsk: 3, sentences: ["明天有足球比赛。"] },
  { id: 375, hanzi: "赢", pinyin: "yíng", meaning: "Gagner", category: "verbes", hsk: 3, sentences: ["我们赢了比赛！"] },
  { id: 376, hanzi: "输", pinyin: "shū", meaning: "Perdre", category: "verbes", hsk: 3, sentences: ["他们输了。"] },
  { id: 377, hanzi: "练习", pinyin: "liànxí", meaning: "S'entraîner", category: "verbes", hsk: 3, sentences: ["我每天练习写汉字。"] },
  { id: 378, hanzi: "复习", pinyin: "fùxí", meaning: "Réviser", category: "verbes", hsk: 3, sentences: ["考试前要好好复习。"] },
  { id: 379, hanzi: "提高", pinyin: "tígāo", meaning: "Améliorer", category: "verbes", hsk: 3, sentences: ["我想提高我的中文水平。"] },
  { id: 380, hanzi: "解决", pinyin: "jiějué", meaning: "Résoudre", category: "verbes", hsk: 3, sentences: ["我们要解决这个问题。"] },
  { id: 381, hanzi: "发现", pinyin: "fāxiàn", meaning: "Découvrir", category: "verbes", hsk: 3, sentences: ["我发现了一个好地方。"] },
  { id: 382, hanzi: "表示", pinyin: "biǎoshì", meaning: "Exprimer", category: "verbes", hsk: 3, sentences: ["他表示感谢。"] },
  { id: 383, hanzi: "解释", pinyin: "jiěshì", meaning: "Expliquer", category: "verbes", hsk: 3, sentences: ["请你解释一下。"] },
  { id: 384, hanzi: "翻译", pinyin: "fānyì", meaning: "Traduire", category: "verbes", hsk: 3, sentences: ["请帮我翻译这句话。"] },
  { id: 385, hanzi: "检查", pinyin: "jiǎnchá", meaning: "Vérifier", category: "verbes", hsk: 3, sentences: ["医生给我检查身体。"] },
  { id: 386, hanzi: "保护", pinyin: "bǎohù", meaning: "Protéger", category: "verbes", hsk: 3, sentences: ["我们要保护环境。"] },
  { id: 387, hanzi: "节约", pinyin: "jiéyuē", meaning: "Économiser", category: "verbes", hsk: 3, sentences: ["请节约用水。"] },
  { id: 388, hanzi: "浪费", pinyin: "làngfèi", meaning: "Gaspiller", category: "verbes", hsk: 3, sentences: ["不要浪费食物。"] },
  { id: 389, hanzi: "放弃", pinyin: "fàngqì", meaning: "Abandonner", category: "verbes", hsk: 3, sentences: ["不要放弃！"] },
  { id: 390, hanzi: "坚持", pinyin: "jiānchí", meaning: "Persévérer", category: "verbes", hsk: 3, sentences: ["你要坚持下去。"] },
  { id: 391, hanzi: "成功", pinyin: "chénggōng", meaning: "Réussir", category: "verbes", hsk: 3, sentences: ["他终于成功了。"] },
  { id: 392, hanzi: "失败", pinyin: "shībài", meaning: "Échouer", category: "verbes", hsk: 3, sentences: ["失败是成功之母。"] },
  { id: 393, hanzi: "接受", pinyin: "jiēshòu", meaning: "Accepter", category: "verbes", hsk: 3, sentences: ["我接受你的建议。"] },
  { id: 394, hanzi: "拿", pinyin: "ná", meaning: "Prendre", category: "verbes", hsk: 3, sentences: ["请拿一本书。"] },
  { id: 395, hanzi: "放", pinyin: "fàng", meaning: "Poser/mettre", category: "verbes", hsk: 3, sentences: ["请把书放在桌子上。"] },
  { id: 396, hanzi: "拉", pinyin: "lā", meaning: "Tirer", category: "verbes", hsk: 3, sentences: ["请拉开门。"] },
  { id: 397, hanzi: "推", pinyin: "tuī", meaning: "Pousser", category: "verbes", hsk: 3, sentences: ["请推开窗户。"] },
  { id: 398, hanzi: "举", pinyin: "jǔ", meaning: "Lever/soulever", category: "verbes", hsk: 3, sentences: ["请举手。"] },
  { id: 399, hanzi: "扔", pinyin: "rēng", meaning: "Jeter", category: "verbes", hsk: 3, sentences: ["不要乱扔垃圾。"] },
  { id: 400, hanzi: "修理", pinyin: "xiūlǐ", meaning: "Réparer", category: "verbes", hsk: 3, sentences: ["他在修理自行车。"] },
  { id: 401, hanzi: "打扫", pinyin: "dǎsǎo", meaning: "Nettoyer", category: "verbes", hsk: 3, sentences: ["我在打扫房间。"] },
  { id: 402, hanzi: "洗", pinyin: "xǐ", meaning: "Laver", category: "verbes", hsk: 3, sentences: ["我要洗衣服。"] },
  { id: 403, hanzi: "穿", pinyin: "chuān", meaning: "Porter (vêtement)", category: "verbes", hsk: 3, sentences: ["今天穿什么衣服？"] },
  { id: 404, hanzi: "戴", pinyin: "dài", meaning: "Porter (accessoire)", category: "verbes", hsk: 3, sentences: ["她戴了一顶帽子。"] },
  { id: 405, hanzi: "脱", pinyin: "tuō", meaning: "Enlever (vêtement)", category: "verbes", hsk: 3, sentences: ["进门请脱鞋。"] },
  { id: 406, hanzi: "请假", pinyin: "qǐngjià", meaning: "Demander un congé", category: "verbes", hsk: 3, sentences: ["我想请一天假。"] },
  { id: 407, hanzi: "搬", pinyin: "bān", meaning: "Déménager", category: "verbes", hsk: 3, sentences: ["他搬到新家了。"] },
  { id: 408, hanzi: "寄", pinyin: "jì", meaning: "Envoyer (courrier)", category: "verbes", hsk: 3, sentences: ["我要寄一封信。"] },
  { id: 409, hanzi: "借", pinyin: "jiè", meaning: "Emprunter/prêter", category: "verbes", hsk: 3, sentences: ["我想借一本书。"] },
  { id: 410, hanzi: "还", pinyin: "huán", meaning: "Rendre", category: "verbes", hsk: 3, sentences: ["请把书还给我。"] },
  { id: 411, hanzi: "挂", pinyin: "guà", meaning: "Accrocher", category: "verbes", hsk: 3, sentences: ["把画挂在墙上。"] },
  { id: 412, hanzi: "关", pinyin: "guān", meaning: "Fermer", category: "verbes", hsk: 3, sentences: ["请关门。"] },
  { id: 413, hanzi: "敲", pinyin: "qiāo", meaning: "Frapper (porte)", category: "verbes", hsk: 3, sentences: ["有人敲门。"] },
  { id: 414, hanzi: "数", pinyin: "shǔ", meaning: "Compter", category: "verbes", hsk: 3, sentences: ["请数一数有多少人。"] },
  { id: 415, hanzi: "称", pinyin: "chēng", meaning: "Peser", category: "verbes", hsk: 3, sentences: ["请称一下这个苹果。"] },
  { id: 416, hanzi: "切", pinyin: "qiē", meaning: "Couper", category: "verbes", hsk: 3, sentences: ["请帮我切菜。"] },
  { id: 417, hanzi: "倒", pinyin: "dào", meaning: "Verser", category: "verbes", hsk: 3, sentences: ["请倒一杯水。"] },
  { id: 418, hanzi: "烤", pinyin: "kǎo", meaning: "Griller", category: "verbes", hsk: 3, sentences: ["我们烤肉吧。"] },
  { id: 419, hanzi: "煮", pinyin: "zhǔ", meaning: "Bouillir/cuire", category: "verbes", hsk: 3, sentences: ["我在煮饭。"] },
  { id: 420, hanzi: "尝", pinyin: "cháng", meaning: "Goûter", category: "verbes", hsk: 3, sentences: ["你尝尝这道菜。"] },
  { id: 421, hanzi: "闻", pinyin: "wén", meaning: "Sentir (odeur)", category: "verbes", hsk: 3, sentences: ["你闻闻这朵花。"] },
  { id: 422, hanzi: "碰", pinyin: "pèng", meaning: "Toucher", category: "verbes", hsk: 3, sentences: ["不要碰那个东西。"] },
  { id: 423, hanzi: "摔", pinyin: "shuāi", meaning: "Tomber", category: "verbes", hsk: 3, sentences: ["小心别摔了。"] },
  { id: 424, hanzi: "哭", pinyin: "kū", meaning: "Pleurer", category: "verbes", hsk: 3, sentences: ["孩子在哭。"] },
  { id: 425, hanzi: "笑", pinyin: "xiào", meaning: "Rire", category: "verbes", hsk: 3, sentences: ["大家都在笑。"] },
  { id: 426, hanzi: "道歉", pinyin: "dàoqiàn", meaning: "S'excuser", category: "verbes", hsk: 3, sentences: ["他向我道歉了。"] },
  { id: 427, hanzi: "感谢", pinyin: "gǎnxiè", meaning: "Remercier", category: "verbes", hsk: 3, sentences: ["感谢你的帮助。"] },

  // === HSK3 — OBJETS ===
  { id: 428, hanzi: "钥匙", pinyin: "yàoshi", meaning: "Clé", category: "objets", hsk: 3, sentences: ["我找不到钥匙。"] },
  { id: 429, hanzi: "空调", pinyin: "kōngtiáo", meaning: "Climatisation", category: "objets", hsk: 3, sentences: ["请打开空调。"] },
  { id: 430, hanzi: "冰箱", pinyin: "bīngxiāng", meaning: "Réfrigérateur", category: "objets", hsk: 3, sentences: ["牛奶在冰箱里。"] },
  { id: 431, hanzi: "洗衣机", pinyin: "xǐyījī", meaning: "Machine à laver", category: "objets", hsk: 3, sentences: ["洗衣机坏了。"] },
  { id: 432, hanzi: "电梯", pinyin: "diàntī", meaning: "Ascenseur", category: "objets", hsk: 3, sentences: ["我们坐电梯上去。"] },
  { id: 433, hanzi: "筷子", pinyin: "kuàizi", meaning: "Baguettes", category: "objets", hsk: 3, sentences: ["你会用筷子吗？"] },
  { id: 434, hanzi: "盘子", pinyin: "pánzi", meaning: "Assiette", category: "objets", hsk: 3, sentences: ["请把盘子洗了。"] },
  { id: 435, hanzi: "碗", pinyin: "wǎn", meaning: "Bol", category: "objets", hsk: 3, sentences: ["给我一个碗。"] },
  { id: 436, hanzi: "勺子", pinyin: "sháozi", meaning: "Cuillère", category: "objets", hsk: 3, sentences: ["用勺子喝汤。"] },
  { id: 437, hanzi: "刀", pinyin: "dāo", meaning: "Couteau", category: "objets", hsk: 3, sentences: ["这把刀很锋利。"] },
  { id: 438, hanzi: "叉子", pinyin: "chāzi", meaning: "Fourchette", category: "objets", hsk: 3, sentences: ["外国人用叉子吃饭。"] },
  { id: 439, hanzi: "瓶子", pinyin: "píngzi", meaning: "Bouteille", category: "objets", hsk: 3, sentences: ["这个瓶子里有水。"] },
  { id: 440, hanzi: "盒子", pinyin: "hézi", meaning: "Boîte", category: "objets", hsk: 3, sentences: ["盒子里有什么？"] },
  { id: 441, hanzi: "袋子", pinyin: "dàizi", meaning: "Sac", category: "objets", hsk: 3, sentences: ["请给我一个袋子。"] },
  { id: 442, hanzi: "伞", pinyin: "sǎn", meaning: "Parapluie", category: "objets", hsk: 3, sentences: ["下雨了，带伞吧。"] },
  { id: 443, hanzi: "毛巾", pinyin: "máojīn", meaning: "Serviette", category: "objets", hsk: 3, sentences: ["给我一条毛巾。"] },
  { id: 444, hanzi: "镜子", pinyin: "jìngzi", meaning: "Miroir", category: "objets", hsk: 3, sentences: ["她在照镜子。"] },
  { id: 445, hanzi: "灯", pinyin: "dēng", meaning: "Lampe", category: "objets", hsk: 3, sentences: ["请打开灯。"] },
  { id: 446, hanzi: "沙发", pinyin: "shāfā", meaning: "Canapé", category: "objets", hsk: 3, sentences: ["请坐在沙发上。"] },
  { id: 447, hanzi: "床", pinyin: "chuáng", meaning: "Lit", category: "objets", hsk: 3, sentences: ["我要上床睡觉了。"] },
  { id: 448, hanzi: "柜子", pinyin: "guìzi", meaning: "Armoire", category: "objets", hsk: 3, sentences: ["衣服在柜子里。"] },
  { id: 449, hanzi: "信用卡", pinyin: "xìnyòngkǎ", meaning: "Carte de crédit", category: "objets", hsk: 3, sentences: ["可以用信用卡吗？"] },
  { id: 450, hanzi: "皮箱", pinyin: "píxiāng", meaning: "Valise", category: "objets", hsk: 3, sentences: ["我的皮箱很重。"] },
  { id: 451, hanzi: "文件", pinyin: "wénjiàn", meaning: "Document", category: "objets", hsk: 3, sentences: ["请把文件给我。"] },
  { id: 452, hanzi: "材料", pinyin: "cáiliào", meaning: "Matériel", category: "objets", hsk: 3, sentences: ["准备好材料了吗？"] },

  // === HSK3 — LIEUX ===
  { id: 453, hanzi: "博物馆", pinyin: "bówùguǎn", meaning: "Musée", category: "lieux", hsk: 3, sentences: ["我们去博物馆看看。"] },
  { id: 454, hanzi: "体育馆", pinyin: "tǐyùguǎn", meaning: "Stade/gymnase", category: "lieux", hsk: 3, sentences: ["体育馆里有很多人。"] },
  { id: 455, hanzi: "电影院", pinyin: "diànyǐngyuàn", meaning: "Cinéma", category: "lieux", hsk: 3, sentences: ["我们去电影院看电影。"] },
  { id: 456, hanzi: "医务室", pinyin: "yīwùshì", meaning: "Infirmerie", category: "lieux", hsk: 3, sentences: ["学校有医务室。"] },
  { id: 457, hanzi: "餐厅", pinyin: "cāntīng", meaning: "Restaurant/cantine", category: "lieux", hsk: 3, sentences: ["我们去餐厅吃饭。"] },
  { id: 458, hanzi: "咖啡厅", pinyin: "kāfēitīng", meaning: "Café (lieu)", category: "lieux", hsk: 3, sentences: ["我们在咖啡厅见面。"] },
  { id: 459, hanzi: "书店", pinyin: "shūdiàn", meaning: "Librairie", category: "lieux", hsk: 3, sentences: ["我去书店买书。"] },
  { id: 460, hanzi: "药店", pinyin: "yàodiàn", meaning: "Pharmacie", category: "lieux", hsk: 3, sentences: ["附近有药店吗？"] },
  { id: 461, hanzi: "加油站", pinyin: "jiāyóuzhàn", meaning: "Station-service", category: "lieux", hsk: 3, sentences: ["前面有加油站。"] },
  { id: 462, hanzi: "停车场", pinyin: "tíngchēchǎng", meaning: "Parking", category: "lieux", hsk: 3, sentences: ["停车场在哪儿？"] },
  { id: 463, hanzi: "十字路口", pinyin: "shízìlùkǒu", meaning: "Carrefour", category: "lieux", hsk: 3, sentences: ["到十字路口往左拐。"] },
  { id: 464, hanzi: "桥", pinyin: "qiáo", meaning: "Pont", category: "lieux", hsk: 3, sentences: ["过了桥就到了。"] },
  { id: 465, hanzi: "广场", pinyin: "guǎngchǎng", meaning: "Place (publique)", category: "lieux", hsk: 3, sentences: ["天安门广场很大。"] },
  { id: 466, hanzi: "海边", pinyin: "hǎibiān", meaning: "Bord de mer", category: "lieux", hsk: 3, sentences: ["夏天我去海边玩。"] },
  { id: 467, hanzi: "农村", pinyin: "nóngcūn", meaning: "Campagne", category: "lieux", hsk: 3, sentences: ["他来自农村。"] },
  { id: 468, hanzi: "城市", pinyin: "chéngshì", meaning: "Ville", category: "lieux", hsk: 3, sentences: ["北京是一个大城市。"] },
  { id: 469, hanzi: "首都", pinyin: "shǒudū", meaning: "Capitale", category: "lieux", hsk: 3, sentences: ["北京是中国的首都。"] },
  { id: 470, hanzi: "国家", pinyin: "guójiā", meaning: "Pays", category: "lieux", hsk: 3, sentences: ["中国是一个大国家。"] },
  { id: 471, hanzi: "地方", pinyin: "dìfang", meaning: "Endroit", category: "lieux", hsk: 3, sentences: ["这个地方很漂亮。"] },
  { id: 472, hanzi: "距离", pinyin: "jùlí", meaning: "Distance", category: "lieux", hsk: 3, sentences: ["两个城市的距离很远。"] },
  { id: 473, hanzi: "方向", pinyin: "fāngxiàng", meaning: "Direction", category: "lieux", hsk: 3, sentences: ["你走错方向了。"] },
  { id: 474, hanzi: "中间", pinyin: "zhōngjiān", meaning: "Au milieu", category: "lieux", hsk: 3, sentences: ["他坐在中间。"] },
  { id: 475, hanzi: "底下", pinyin: "dǐxia", meaning: "En bas/en dessous", category: "lieux", hsk: 3, sentences: ["猫在桌子底下。"] },
  { id: 476, hanzi: "东", pinyin: "dōng", meaning: "Est", category: "lieux", hsk: 3, sentences: ["太阳从东边升起。"] },
  { id: 477, hanzi: "西", pinyin: "xī", meaning: "Ouest", category: "lieux", hsk: 3, sentences: ["太阳从西边落下。"] },

  // === HSK3 — ADJECTIFS ===
  { id: 478, hanzi: "聪明", pinyin: "cōngming", meaning: "Intelligent", category: "adjectifs", hsk: 3, sentences: ["这个孩子很聪明。"] },
  { id: 479, hanzi: "笨", pinyin: "bèn", meaning: "Stupide", category: "adjectifs", hsk: 3, sentences: ["我不笨！"] },
  { id: 480, hanzi: "认真", pinyin: "rènzhēn", meaning: "Sérieux", category: "adjectifs", hsk: 3, sentences: ["他学习很认真。"] },
  { id: 481, hanzi: "马虎", pinyin: "mǎhu", meaning: "Négligent", category: "adjectifs", hsk: 3, sentences: ["做事不要太马虎。"] },
  { id: 482, hanzi: "勇敢", pinyin: "yǒnggǎn", meaning: "Courageux", category: "adjectifs", hsk: 3, sentences: ["他是一个勇敢的人。"] },
  { id: 483, hanzi: "害怕", pinyin: "hàipà", meaning: "Avoir peur", category: "adjectifs", hsk: 3, sentences: ["不要害怕。"] },
  { id: 484, hanzi: "激动", pinyin: "jīdòng", meaning: "Excité", category: "adjectifs", hsk: 3, sentences: ["他非常激动。"] },
  { id: 485, hanzi: "紧张", pinyin: "jǐnzhāng", meaning: "Nerveux", category: "adjectifs", hsk: 3, sentences: ["考试前我很紧张。"] },
  { id: 486, hanzi: "难过", pinyin: "nánguò", meaning: "Triste", category: "adjectifs", hsk: 3, sentences: ["听到这个消息我很难过。"] },
  { id: 487, hanzi: "着急", pinyin: "zháojí", meaning: "Pressé/anxieux", category: "adjectifs", hsk: 3, sentences: ["别着急，慢慢来。"] },
  { id: 488, hanzi: "满意", pinyin: "mǎnyì", meaning: "Satisfait", category: "adjectifs", hsk: 3, sentences: ["我对结果很满意。"] },
  { id: 489, hanzi: "失望", pinyin: "shīwàng", meaning: "Déçu", category: "adjectifs", hsk: 3, sentences: ["他很失望。"] },
  { id: 490, hanzi: "无聊", pinyin: "wúliáo", meaning: "Ennuyeux", category: "adjectifs", hsk: 3, sentences: ["这部电影很无聊。"] },
  { id: 491, hanzi: "有趣", pinyin: "yǒuqù", meaning: "Intéressant", category: "adjectifs", hsk: 3, sentences: ["这本书很有趣。"] },
  { id: 492, hanzi: "丰富", pinyin: "fēngfù", meaning: "Riche/varié", category: "adjectifs", hsk: 3, sentences: ["这里的菜很丰富。"] },
  { id: 493, hanzi: "复杂", pinyin: "fùzá", meaning: "Compliqué", category: "adjectifs", hsk: 3, sentences: ["这个问题很复杂。"] },
  { id: 494, hanzi: "简单", pinyin: "jiǎndān", meaning: "Simple", category: "adjectifs", hsk: 3, sentences: ["这道题很简单。"] },
  { id: 495, hanzi: "普通", pinyin: "pǔtōng", meaning: "Ordinaire", category: "adjectifs", hsk: 3, sentences: ["我是一个普通人。"] },
  { id: 496, hanzi: "特别", pinyin: "tèbié", meaning: "Spécial", category: "adjectifs", hsk: 3, sentences: ["今天是一个特别的日子。"] },
  { id: 497, hanzi: "正常", pinyin: "zhèngcháng", meaning: "Normal", category: "adjectifs", hsk: 3, sentences: ["一切都很正常。"] },
  { id: 498, hanzi: "合适", pinyin: "héshì", meaning: "Convenable", category: "adjectifs", hsk: 3, sentences: ["这件衣服很合适。"] },
  { id: 499, hanzi: "严格", pinyin: "yángé", meaning: "Strict", category: "adjectifs", hsk: 3, sentences: ["老师很严格。"] },
  { id: 500, hanzi: "温柔", pinyin: "wēnróu", meaning: "Doux/tendre", category: "adjectifs", hsk: 3, sentences: ["她很温柔。"] },
  { id: 501, hanzi: "热情", pinyin: "rèqíng", meaning: "Chaleureux", category: "adjectifs", hsk: 3, sentences: ["中国人很热情。"] },
  { id: 502, hanzi: "冷淡", pinyin: "lěngdàn", meaning: "Froid (personne)", category: "adjectifs", hsk: 3, sentences: ["他对人很冷淡。"] },
  { id: 503, hanzi: "厚", pinyin: "hòu", meaning: "Épais", category: "adjectifs", hsk: 3, sentences: ["这本书很厚。"] },
  { id: 504, hanzi: "薄", pinyin: "báo", meaning: "Mince/fin", category: "adjectifs", hsk: 3, sentences: ["这张纸很薄。"] },
  { id: 505, hanzi: "深", pinyin: "shēn", meaning: "Profond", category: "adjectifs", hsk: 3, sentences: ["这条河很深。"] },
  { id: 506, hanzi: "浅", pinyin: "qiǎn", meaning: "Superficiel/clair", category: "adjectifs", hsk: 3, sentences: ["这里的水很浅。"] },
  { id: 507, hanzi: "湿", pinyin: "shī", meaning: "Humide", category: "adjectifs", hsk: 3, sentences: ["衣服还是湿的。"] },

  // === HSK3 — OUTILS ===
  { id: 508, hanzi: "不仅", pinyin: "bùjǐn", meaning: "Non seulement", category: "outils", hsk: 3, sentences: ["他不仅聪明，而且努力。"] },
  { id: 509, hanzi: "而且", pinyin: "érqiě", meaning: "De plus", category: "outils", hsk: 3, sentences: ["这个东西便宜而且好。"] },
  { id: 510, hanzi: "另外", pinyin: "lìngwài", meaning: "En outre", category: "outils", hsk: 3, sentences: ["另外还有一件事。"] },
  { id: 511, hanzi: "然而", pinyin: "rán'ér", meaning: "Cependant", category: "outils", hsk: 3, sentences: ["他很努力，然而没有成功。"] },
  { id: 512, hanzi: "于是", pinyin: "yúshì", meaning: "Alors", category: "outils", hsk: 3, sentences: ["天下雨了，于是我回家了。"] },
  { id: 513, hanzi: "否则", pinyin: "fǒuzé", meaning: "Sinon", category: "outils", hsk: 3, sentences: ["快走，否则要迟到了。"] },
  { id: 514, hanzi: "无论", pinyin: "wúlùn", meaning: "Quel que soit", category: "outils", hsk: 3, sentences: ["无论如何我都支持你。"] },
  { id: 515, hanzi: "即使", pinyin: "jíshǐ", meaning: "Même si", category: "outils", hsk: 3, sentences: ["即使下雨，我也去。"] },
  { id: 516, hanzi: "只要", pinyin: "zhǐyào", meaning: "Pourvu que", category: "outils", hsk: 3, sentences: ["只要努力就会成功。"] },
  { id: 517, hanzi: "除了", pinyin: "chúle", meaning: "Sauf/en plus de", category: "outils", hsk: 3, sentences: ["除了中文，我还学英语。"] },
  { id: 518, hanzi: "按照", pinyin: "ànzhào", meaning: "Selon", category: "outils", hsk: 3, sentences: ["请按照规定做。"] },
  { id: 519, hanzi: "根据", pinyin: "gēnjù", meaning: "Selon/d'après", category: "outils", hsk: 3, sentences: ["根据天气预报，明天有雨。"] },
  { id: 520, hanzi: "通过", pinyin: "tōngguò", meaning: "Par/à travers", category: "outils", hsk: 3, sentences: ["通过学习我提高了中文。"] },
  { id: 521, hanzi: "为了", pinyin: "wèile", meaning: "Pour/afin de", category: "outils", hsk: 3, sentences: ["为了学好中文，我每天练习。"] },
  { id: 522, hanzi: "关于", pinyin: "guānyú", meaning: "Concernant", category: "outils", hsk: 3, sentences: ["关于这个问题，我有话说。"] },
  { id: 523, hanzi: "对于", pinyin: "duìyú", meaning: "En ce qui concerne", category: "outils", hsk: 3, sentences: ["对于学生来说，学习很重要。"] },
  { id: 524, hanzi: "之", pinyin: "zhī", meaning: "De (littéraire)", category: "outils", hsk: 3, sentences: ["三分之一。"] },
  { id: 525, hanzi: "把", pinyin: "bǎ", meaning: "Particule (BA)", category: "outils", hsk: 3, sentences: ["把门关上。"] },
  { id: 526, hanzi: "被", pinyin: "bèi", meaning: "Particule (passif)", category: "outils", hsk: 3, sentences: ["杯子被打破了。"] },
  { id: 527, hanzi: "着", pinyin: "zhe", meaning: "Particule (aspect)", category: "outils", hsk: 3, sentences: ["他笑着说。"] },
  { id: 528, hanzi: "过", pinyin: "guò", meaning: "Particule (expérience)", category: "outils", hsk: 3, sentences: ["我去过中国。"] },
  { id: 529, hanzi: "地", pinyin: "de", meaning: "Particule (adverbiale)", category: "outils", hsk: 3, sentences: ["他高兴地笑了。"] },
  { id: 530, hanzi: "得", pinyin: "dé", meaning: "Particule (résultat)", category: "outils", hsk: 3, sentences: ["他跑得很快。"] },
  { id: 531, hanzi: "就", pinyin: "jiù", meaning: "Alors/justement", category: "outils", hsk: 3, sentences: ["我马上就来。"] },
  { id: 532, hanzi: "才", pinyin: "cái", meaning: "Seulement alors", category: "outils", hsk: 3, sentences: ["他十点才来。"] },
  { id: 533, hanzi: "却", pinyin: "què", meaning: "Pourtant", category: "outils", hsk: 3, sentences: ["他很聪明，却不努力。"] },
  { id: 534, hanzi: "倒", pinyin: "dào", meaning: "Au contraire", category: "outils", hsk: 3, sentences: ["他倒是很高兴。"] },
  { id: 535, hanzi: "差不多", pinyin: "chàbuduō", meaning: "À peu près", category: "outils", hsk: 3, sentences: ["差不多了。"] },
  { id: 536, hanzi: "几乎", pinyin: "jīhū", meaning: "Presque", category: "outils", hsk: 3, sentences: ["我几乎忘了。"] },
  { id: 537, hanzi: "大概", pinyin: "dàgài", meaning: "Probablement", category: "outils", hsk: 3, sentences: ["大概要三个小时。"] },
  { id: 538, hanzi: "至少", pinyin: "zhìshǎo", meaning: "Au moins", category: "outils", hsk: 3, sentences: ["至少要学一年。"] },
  { id: 539, hanzi: "甚至", pinyin: "shènzhì", meaning: "Même", category: "outils", hsk: 3, sentences: ["他甚至会说法语。"] },
  { id: 540, hanzi: "尤其", pinyin: "yóuqí", meaning: "Surtout", category: "outils", hsk: 3, sentences: ["我喜欢水果，尤其是苹果。"] },
  { id: 541, hanzi: "首先", pinyin: "shǒuxiān", meaning: "D'abord", category: "outils", hsk: 3, sentences: ["首先我们要准备。"] },
  { id: 542, hanzi: "然后", pinyin: "ránhòu", meaning: "Ensuite", category: "outils", hsk: 3, sentences: ["先吃饭，然后去散步。"] },

  // === HSK3 — MÉTIERS ===
  { id: 543, hanzi: "教授", pinyin: "jiàoshòu", meaning: "Professeur (université)", category: "metiers", hsk: 3, sentences: ["王教授很有名。"] },
  { id: 544, hanzi: "科学家", pinyin: "kēxuéjiā", meaning: "Scientifique", category: "metiers", hsk: 3, sentences: ["他是一位科学家。"] },
  { id: 545, hanzi: "工程师", pinyin: "gōngchéngshī", meaning: "Ingénieur", category: "metiers", hsk: 3, sentences: ["我想当工程师。"] },
  { id: 546, hanzi: "厨师", pinyin: "chúshī", meaning: "Cuisinier", category: "metiers", hsk: 3, sentences: ["这个厨师做菜很好吃。"] },
  { id: 547, hanzi: "农民", pinyin: "nóngmín", meaning: "Paysan", category: "metiers", hsk: 3, sentences: ["农民在田里工作。"] },
  { id: 548, hanzi: "商人", pinyin: "shāngrén", meaning: "Commerçant", category: "metiers", hsk: 3, sentences: ["他是一个成功的商人。"] },
  { id: 549, hanzi: "导游", pinyin: "dǎoyóu", meaning: "Guide touristique", category: "metiers", hsk: 3, sentences: ["导游带我们参观了博物馆。"] },
  { id: 550, hanzi: "翻译", pinyin: "fānyì", meaning: "Traducteur", category: "metiers", hsk: 3, sentences: ["她是一名翻译。"] },
  { id: 551, hanzi: "作家", pinyin: "zuòjiā", meaning: "Écrivain", category: "metiers", hsk: 3, sentences: ["他是一位有名的作家。"] },
  { id: 552, hanzi: "歌手", pinyin: "gēshǒu", meaning: "Chanteur", category: "metiers", hsk: 3, sentences: ["她是我喜欢的歌手。"] },
  { id: 553, hanzi: "画家", pinyin: "huàjiā", meaning: "Peintre", category: "metiers", hsk: 3, sentences: ["这位画家很有名。"] },
  { id: 554, hanzi: "摄影师", pinyin: "shèyǐngshī", meaning: "Photographe", category: "metiers", hsk: 3, sentences: ["摄影师在拍照片。"] },
  { id: 555, hanzi: "设计师", pinyin: "shèjìshī", meaning: "Designer", category: "metiers", hsk: 3, sentences: ["她是一名设计师。"] },
  { id: 556, hanzi: "老板", pinyin: "lǎobǎn", meaning: "Patron", category: "metiers", hsk: 3, sentences: ["老板对员工很好。"] },

  // === HSK3 — NATURE ===
  { id: 557, hanzi: "草", pinyin: "cǎo", meaning: "Herbe", category: "nature", hsk: 3, sentences: ["草地上有很多花。"] },
  { id: 558, hanzi: "叶子", pinyin: "yèzi", meaning: "Feuille", category: "nature", hsk: 3, sentences: ["秋天叶子变红了。"] },
  { id: 559, hanzi: "森林", pinyin: "sēnlín", meaning: "Forêt", category: "nature", hsk: 3, sentences: ["森林里有很多动物。"] },
  { id: 560, hanzi: "沙漠", pinyin: "shāmò", meaning: "Désert", category: "nature", hsk: 3, sentences: ["沙漠里很热。"] },
  { id: 561, hanzi: "海洋", pinyin: "hǎiyáng", meaning: "Océan", category: "nature", hsk: 3, sentences: ["海洋很大。"] },
  { id: 562, hanzi: "湖", pinyin: "hú", meaning: "Lac", category: "nature", hsk: 3, sentences: ["湖水很清。"] },
  { id: 563, hanzi: "岛", pinyin: "dǎo", meaning: "Île", category: "nature", hsk: 3, sentences: ["那个岛很漂亮。"] },
  { id: 564, hanzi: "瀑布", pinyin: "pùbù", meaning: "Cascade", category: "nature", hsk: 3, sentences: ["瀑布非常壮观。"] },
  { id: 565, hanzi: "地震", pinyin: "dìzhèn", meaning: "Tremblement de terre", category: "nature", hsk: 3, sentences: ["昨天发生了地震。"] },
  { id: 566, hanzi: "洪水", pinyin: "hóngshuǐ", meaning: "Inondation", category: "nature", hsk: 3, sentences: ["洪水很危险。"] },
  { id: 567, hanzi: "星星", pinyin: "xīngxing", meaning: "Étoile", category: "nature", hsk: 3, sentences: ["晚上可以看到星星。"] },
  { id: 568, hanzi: "月亮", pinyin: "yuèliang", meaning: "Lune", category: "nature", hsk: 3, sentences: ["今晚的月亮很圆。"] },
  { id: 569, hanzi: "空气", pinyin: "kōngqì", meaning: "Air", category: "nature", hsk: 3, sentences: ["山上的空气很新鲜。"] },
  { id: 570, hanzi: "气候", pinyin: "qìhòu", meaning: "Climat", category: "nature", hsk: 3, sentences: ["这里的气候很好。"] },
  { id: 571, hanzi: "温度", pinyin: "wēndù", meaning: "Température", category: "nature", hsk: 3, sentences: ["今天的温度很高。"] },
  { id: 572, hanzi: "天空", pinyin: "tiānkōng", meaning: "Ciel", category: "nature", hsk: 3, sentences: ["天空很蓝。"] },
  { id: 573, hanzi: "彩虹", pinyin: "cǎihóng", meaning: "Arc-en-ciel", category: "nature", hsk: 3, sentences: ["雨后出现了彩虹。"] },
  { id: 574, hanzi: "闪电", pinyin: "shǎndiàn", meaning: "Éclair", category: "nature", hsk: 3, sentences: ["闪电很亮。"] },
  { id: 575, hanzi: "雷", pinyin: "léi", meaning: "Tonnerre", category: "nature", hsk: 3, sentences: ["打雷了，要下雨了。"] },
  { id: 576, hanzi: "雾", pinyin: "wù", meaning: "Brouillard", category: "nature", hsk: 3, sentences: ["今天有大雾。"] },
  { id: 577, hanzi: "冰", pinyin: "bīng", meaning: "Glace", category: "nature", hsk: 3, sentences: ["冬天河里有冰。"] },
  { id: 578, hanzi: "泥", pinyin: "ní", meaning: "Boue", category: "nature", hsk: 3, sentences: ["下雨后路上有泥。"] },
  { id: 579, hanzi: "石头", pinyin: "shítou", meaning: "Pierre", category: "nature", hsk: 3, sentences: ["路上有一块大石头。"] },
  { id: 580, hanzi: "沙子", pinyin: "shāzi", meaning: "Sable", category: "nature", hsk: 3, sentences: ["海边有很多沙子。"] },
  { id: 581, hanzi: "火", pinyin: "huǒ", meaning: "Feu", category: "nature", hsk: 3, sentences: ["不要玩火。"] },

  // === HSK3 — ANIMAUX ===
  { id: 582, hanzi: "蛇", pinyin: "shé", meaning: "Serpent", category: "animaux", hsk: 3, sentences: ["我害怕蛇。"] },
  { id: 583, hanzi: "猴子", pinyin: "hóuzi", meaning: "Singe", category: "animaux", hsk: 3, sentences: ["猴子很聪明。"] },
  { id: 584, hanzi: "大象", pinyin: "dàxiàng", meaning: "Éléphant", category: "animaux", hsk: 3, sentences: ["大象很大。"] },
  { id: 585, hanzi: "狮子", pinyin: "shīzi", meaning: "Lion", category: "animaux", hsk: 3, sentences: ["狮子是丛林之王。"] },
  { id: 586, hanzi: "狼", pinyin: "láng", meaning: "Loup", category: "animaux", hsk: 3, sentences: ["狼跑得很快。"] },
  { id: 587, hanzi: "鲨鱼", pinyin: "shāyú", meaning: "Requin", category: "animaux", hsk: 3, sentences: ["鲨鱼生活在海里。"] },
  { id: 588, hanzi: "海豚", pinyin: "hǎitún", meaning: "Dauphin", category: "animaux", hsk: 3, sentences: ["海豚很聪明。"] },
  { id: 589, hanzi: "鹰", pinyin: "yīng", meaning: "Aigle", category: "animaux", hsk: 3, sentences: ["鹰飞得很高。"] },
  { id: 590, hanzi: "蝴蝶", pinyin: "húdié", meaning: "Papillon", category: "animaux", hsk: 3, sentences: ["花园里有很多蝴蝶。"] },
  { id: 591, hanzi: "蜜蜂", pinyin: "mìfēng", meaning: "Abeille", category: "animaux", hsk: 3, sentences: ["蜜蜂在采花蜜。"] },
  { id: 592, hanzi: "蚂蚁", pinyin: "mǎyǐ", meaning: "Fourmi", category: "animaux", hsk: 3, sentences: ["蚂蚁很勤劳。"] },
  { id: 593, hanzi: "蚊子", pinyin: "wénzi", meaning: "Moustique", category: "animaux", hsk: 3, sentences: ["夏天蚊子很多。"] },
  { id: 594, hanzi: "乌龟", pinyin: "wūguī", meaning: "Tortue", category: "animaux", hsk: 3, sentences: ["乌龟走得很慢。"] },
  { id: 595, hanzi: "鹿", pinyin: "lù", meaning: "Cerf", category: "animaux", hsk: 3, sentences: ["森林里有鹿。"] },
  { id: 596, hanzi: "鸭子", pinyin: "yāzi", meaning: "Canard", category: "animaux", hsk: 3, sentences: ["鸭子在水里游。"] },
  { id: 597, hanzi: "鹅", pinyin: "é", meaning: "Oie", category: "animaux", hsk: 3, sentences: ["农场里有鹅。"] },
  { id: 598, hanzi: "蜘蛛", pinyin: "zhīzhū", meaning: "Araignée", category: "animaux", hsk: 3, sentences: ["蜘蛛在织网。"] },
  { id: 599, hanzi: "龙", pinyin: "lóng", meaning: "Dragon", category: "animaux", hsk: 3, sentences: ["龙是中国文化的象征。"] },
  { id: 600, hanzi: "凤凰", pinyin: "fènghuáng", meaning: "Phénix", category: "animaux", hsk: 3, sentences: ["凤凰是传说中的鸟。"] },
  { id: 601, hanzi: "虫子", pinyin: "chóngzi", meaning: "Insecte", category: "animaux", hsk: 3, sentences: ["我不喜欢虫子。"] },

  // === HSK3 — CORPS ===
  { id: 602, hanzi: "肩膀", pinyin: "jiānbǎng", meaning: "Épaule", category: "corps", hsk: 3, sentences: ["我的肩膀很疼。"] },
  { id: 603, hanzi: "胳膊", pinyin: "gēbo", meaning: "Bras", category: "corps", hsk: 3, sentences: ["他的胳膊很长。"] },
  { id: 604, hanzi: "手指", pinyin: "shǒuzhǐ", meaning: "Doigt", category: "corps", hsk: 3, sentences: ["他有十个手指。"] },
  { id: 605, hanzi: "膝盖", pinyin: "xīgài", meaning: "Genou", category: "corps", hsk: 3, sentences: ["我的膝盖受伤了。"] },
  { id: 606, hanzi: "腰", pinyin: "yāo", meaning: "Taille/dos", category: "corps", hsk: 3, sentences: ["我的腰有点疼。"] },
  { id: 607, hanzi: "背", pinyin: "bèi", meaning: "Dos", category: "corps", hsk: 3, sentences: ["他背很直。"] },
  { id: 608, hanzi: "胸", pinyin: "xiōng", meaning: "Poitrine", category: "corps", hsk: 3, sentences: ["他胸口疼。"] },
  { id: 609, hanzi: "肚子", pinyin: "dùzi", meaning: "Ventre", category: "corps", hsk: 3, sentences: ["我肚子饿了。"] },
  { id: 610, hanzi: "皮肤", pinyin: "pífū", meaning: "Peau", category: "corps", hsk: 3, sentences: ["她的皮肤很好。"] },
  { id: 611, hanzi: "骨头", pinyin: "gǔtou", meaning: "Os", category: "corps", hsk: 3, sentences: ["狗喜欢啃骨头。"] },
  { id: 612, hanzi: "血", pinyin: "xuè", meaning: "Sang", category: "corps", hsk: 3, sentences: ["他流血了。"] },
  { id: 613, hanzi: "心脏", pinyin: "xīnzàng", meaning: "Cœur (organe)", category: "corps", hsk: 3, sentences: ["心脏是很重要的器官。"] },
  { id: 614, hanzi: "肺", pinyin: "fèi", meaning: "Poumons", category: "corps", hsk: 3, sentences: ["吸烟对肺不好。"] },
  { id: 615, hanzi: "胃", pinyin: "wèi", meaning: "Estomac", category: "corps", hsk: 3, sentences: ["我的胃不舒服。"] },
  { id: 616, hanzi: "牙齿", pinyin: "yáchǐ", meaning: "Dents", category: "corps", hsk: 3, sentences: ["要每天刷牙齿。"] },
  { id: 617, hanzi: "舌头", pinyin: "shétou", meaning: "Langue", category: "corps", hsk: 3, sentences: ["舌头可以尝味道。"] },
  { id: 618, hanzi: "头发", pinyin: "tóufa", meaning: "Cheveux", category: "corps", hsk: 3, sentences: ["她的头发很长。"] },
  { id: 619, hanzi: "胡子", pinyin: "húzi", meaning: "Barbe", category: "corps", hsk: 3, sentences: ["他留了胡子。"] },
  { id: 620, hanzi: "脖子", pinyin: "bózi", meaning: "Cou", category: "corps", hsk: 3, sentences: ["长颈鹿的脖子很长。"] },
  { id: 621, hanzi: "指甲", pinyin: "zhǐjia", meaning: "Ongles", category: "corps", hsk: 3, sentences: ["请剪指甲。"] },
  { id: 622, hanzi: "肌肉", pinyin: "jīròu", meaning: "Muscle", category: "corps", hsk: 3, sentences: ["锻炼可以增加肌肉。"] },
  { id: 623, hanzi: "大脑", pinyin: "dànǎo", meaning: "Cerveau", category: "corps", hsk: 3, sentences: ["大脑是人体最重要的器官。"] },
  { id: 624, hanzi: "声音", pinyin: "shēngyīn", meaning: "Voix/son", category: "corps", hsk: 3, sentences: ["她的声音很好听。"] },
  { id: 625, hanzi: "力气", pinyin: "lìqi", meaning: "Force", category: "corps", hsk: 3, sentences: ["他力气很大。"] },
  { id: 626, hanzi: "健康", pinyin: "jiànkāng", meaning: "Santé", category: "corps", hsk: 3, sentences: ["健康最重要。"] },
];

// Category metadata for UI
const CATEGORIES = {
  salutations: { name: "Salutations", icon: "👋", color: "#f0c040" },
  pronoms: { name: "Pronoms", icon: "👤", color: "#60b0f0" },
  nombres: { name: "Nombres", icon: "🔢", color: "#f06060" },
  temps: { name: "Temps", icon: "⏰", color: "#a070e0" },
  famille: { name: "Famille", icon: "👨‍👩‍👧", color: "#f090c0" },
  nourriture: { name: "Nourriture", icon: "🍜", color: "#60d080" },
  verbes: { name: "Verbes", icon: "⚡", color: "#f0a040" },
  adjectifs: { name: "Adjectifs", icon: "✨", color: "#e060e0" },
  lieux: { name: "Lieux", icon: "🏯", color: "#40c0c0" },
  objets: { name: "Objets", icon: "📦", color: "#c0a060" },
  outils: { name: "Mots outils", icon: "🔧", color: "#8090a0" },
  metiers: { name: "Métiers", icon: "💼", color: "#70b070" },
  nature: { name: "Nature", icon: "🌿", color: "#40a060" },
  animaux: { name: "Animaux", icon: "🐾", color: "#c08050" },
  corps: { name: "Corps", icon: "🫀", color: "#e07080" },
};

// Get words by category
function getWordsByCategory(cat) {
  return HSK_DATA.filter(w => w.category === cat);
}

// Get unique first characters for HanziWriter (single char)
function getSingleChars() {
  const chars = new Set();
  HSK_DATA.forEach(w => {
    for (const ch of w.hanzi) {
      chars.add(ch);
    }
  });
  return [...chars];
}
